### ISSUE TITLE
[功能请求]群消息撤回事件与好友消息撤回事件上报

### ISSUE THREAD

**Issue by kagangtuya-star** [LagrangeDev/Lagrange.Core#101]
https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E6%B6%88%E6%81%AF%E6%92%A4%E5%9B%9E

https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E5%A5%BD%E5%8F%8B%E6%B6%88%E6%81%AF%E6%92%A4%E5%9B%9E

onebotv11文档如上。

**Comment by Linwenxuan05** [comment]
Implemented at 26b4b77f4db00c063b780d408904e2d416a76c42
