### ISSUE TITLE
Unsuccessful SSOFrame Payload

### ISSUE THREAD

**Issue by 2mf8** [LagrangeDev/Lagrange.Core#103]
![A066D51CC147FF8F82886AF995551227](https://github.com/LagrangeDev/Lagrange.Core/assets/28614037/057e3fa6-c693-4b16-b3cf-5fbc71f83b88)

**Comment by Linwenxuan05** [comment]
这个报错并不是程序退出的原因 请查看上一个报错

**Comment by 2mf8** [comment]
问题已解决
