### ISSUE TITLE
[Bug Report][Core] Cannot receive Group RecordEntity send by QQMobile

### ISSUE THREAD

**Issue by AkulaKirov** [LagrangeDev/Lagrange.Core#107]
Enviroment:
Using  Lagrange.Core@520c7ab
Windows 11 X64

Action:
A record is sent from QQMobile

Expect:
`GroupMessageEvent` with a `RecordEntity` `MessageChain` would be received

Actual:
`trpc.msg.olpush.OlPushService.MsgPush` is shown but `GroupMessageEvent` is not received

Log: 

```
trce: Lagrange.Core.BotContext[0]
      [ServiceContext] Outgoing SSOFrame: Heartbeat.Alive
// Message send
trce: Lagrange.Core.BotContext[0]
      [ServiceContext] Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush
// And nothing happened
trce: Lagrange.Core.BotContext[0]
      [ServiceContext] Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.Core.BotContext[0]
```

**Comment by Linwenxuan05** [comment]
Fixed at 4de9614be7fb7d845db0f9f5f6b4a014d175bc90
