### ISSUE TITLE
[BUG] 在Linux环境下的路径拼接问题

### ISSUE THREAD

**Issue by Miaoyww** [LagrangeDev/Lagrange.Core#108]
![00aef67129ea21ed1e07d008c6256fa5](https://github.com/LagrangeDev/Lagrange.Core/assets/52089819/59fb784f-ef48-4355-968d-c2ecc79b0fdd)

这是事件相应代码:
```
    async def handle(self) -> None:
        file_path = str(BASE_PATH / 'Image' / '不要放洋屁.jpg')
        msg = CQHTTPMessageSegment.image('file:///' + file_path)
        await self.event.reply(msg)
```

已实测，在Windows平台运行正常。使用其它核心如NoneBot 2运行正常。

**Comment by Linwenxuan05** [comment]
Fixed at https://github.com/LagrangeDev/Lagrange.Core/commit/b424207b40300f3fe2ee3fa1a67a3e3a896b1334
