### ISSUE TITLE
[Feature Request]: 未来是否有计划提供戳一戳功能的支持

### ISSUE THREAD

**Issue by Allenyou1126** [LagrangeDev/Lagrange.Core#123]
### Lagrange项目

Core

### 新需求内容

如题，如果未来NTQQ支持显示戳一戳消息是否会有支持戳一戳消息的接收/发送功能的计划

**Comment by Linwenxuan05** [comment]
先支持再说吧

Allenyou ***@***.***>于2024年2月29日 周四上午11:12写道：

**Comment by wyapx** [comment]
发送已经支持，望周知（

**Comment by Allenyou1126** [comment]
可惜NTQQ现在还是不支持监听戳一戳事件（
要是支持了可就真能把OpenShamork换到Lagrange上来了

**Comment by Linwenxuan05** [comment]
私聊接受Poke已经支持
群的 你催一下腾讯让他们显示

**Comment by msojocs** [comment]
![image](https://github.com/KonataDev/Lagrange.Core/assets/20937135/ac04bfe5-6f23-4427-a91a-d29235c63ee9)

我拿windows 9.9.9-22741的数据，私聊戳一戳也没有body，区分不出对方戳自己还是戳我。

但是戳一戳的撤回就有body。

![image](https://github.com/KonataDev/Lagrange.Core/assets/20937135/b8ea46e1-36b9-4463-9eda-63034f20eab2)

**Comment by Linwenxuan05** [comment]
> ![image](https://private-user-images.githubusercontent.com/20937135/322169791-ac04bfe5-6f23-4427-a91a-d29235c63ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODQ4NjEsIm5iZiI6MTcxMjk4NDU2MSwicGF0aCI6Ii8yMDkzNzEzNS8zMjIxNjk3OTEtYWMwNGJmZTUtNmYyMy00NDI3LWE5MWEtZDI5MjM1YzYzZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA1MDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YjMwODJkYTBjODk4YWY3NDBiYzhkMGMzMzAwMjkxOGI0MWJlNjkzZDkxNDYzZDI4NDBlY2VkYmIzNWJiMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qyQ_-c90-4w04Ai3O7pkslRc1Gk8EIC2OEY3VTb8OG0)
> 
> 我拿windows 9.9.9-22741的数据（9.9.9-22868表现一致），私聊戳一戳也没有body，区分不出对方戳自己还是戳我。
> 
> 但是戳一戳的撤回就有body。
> 
> ![image](https://private-user-images.githubusercontent.com/20937135/322169912-b8ea46e1-36b9-4463-9eda-63034f20eab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODQ4NjEsIm5iZiI6MTcxMjk4NDU2MSwicGF0aCI6Ii8yMDkzNzEzNS8zMjIxNjk5MTItYjhlYTQ2ZTEtMzZiOS00NDYzLTllZGEtNjMwMzRmMjBlYWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA1MDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NDZjNzUxZjYzOGZkYjNlYThhMzAxYWEzNmUyNTQ1NThlNmE3ZmIyYjk3ZmM0ZmUwYjkwYWRiNTRhZDlkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-LN61XqY4TBcwolbAsyAK7pRiiAiwAUjzL3rsq4o8ZA)

按照这个思路来说 是不是可以通过某种拉消息记录的方式来获取群聊/私聊戳

**Comment by msojocs** [comment]
> 按照这个思路来说 是不是可以通过某种拉消息记录的方式来获取群聊/私聊戳

可以试试，不过，我在手机上：
1. 清空本地消息
2. 查看漫游消息
3. 看不到戳一戳的记录

**Comment by Linwenxuan05** [comment]
> > 按照这个思路来说 是不是可以通过某种拉消息记录的方式来获取群聊/私聊戳
> 
> 可以试试，不过，我在手机上：
> 
> 1. 清空本地消息
> 2. 查看漫游消息
> 3. 看不到戳一戳的记录

我这里是可以看到戳一戳的记录的 但是应该走的是独立的Command

**Comment by Allenyou1126** [comment]
最新更新，腾讯在桌面QQNT 9.9.12-25493 中更新了接受群聊头像双击的功能，Lagrange功能又有戏了（

**Comment by MicIsHere** [comment]
蹲一手

> 最新更新，腾讯在桌面QQNT 9.9.12-25493 中更新了接受群聊头像双击的功能，Lagrange功能又有戏了（

**Comment by ishkong** [comment]
已更新，请使用最新版lgr尝试
