### ISSUE TITLE
[Bug?]: 私聊中的回复显示消息已过期

### ISSUE THREAD

**Issue by DarkCWK** [LagrangeDev/Lagrange.Core#129]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）
- [x] 我已经仔细阅读上述内容

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

8e205fc

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

qq私聊bot一条消息, 从控制台获取消息id
向bot发送
```json
{
    "action": "send_private_msg",
    "params": {
        "user_id": 0,
        "message": [
            {
                "type":"reply",
                "data": {
                    "id": 0
                }
            },
            {
                "type": "text",
                "data": {
                    "text": "测试"
                }
            }
        ]
    }
}
```

### 期望的结果是什么？

![图片](https://github.com/LagrangeDev/Lagrange.Core/assets/20531116/39207538-511e-42a0-a2fb-5f2ff642f24c)

### 实际的结果是什么？

![图片](https://github.com/LagrangeDev/Lagrange.Core/assets/20531116/6a62b9f3-8f8e-4f8a-af55-b92e00243865)

**Comment by Linwenxuan05** [comment]
Try 0ebd6b87414afb619f872e85b452b04db2045351

**Comment by Linwenxuan05** [comment]
Fixed at a30c4d29fe93414a7e425cd66c5a688a56e0b4ee
