### ISSUE TITLE
[Feature Request]: 允许配置容器数据文件的权限

### ISSUE THREAD

**Issue by A-kirami** [LagrangeDev/Lagrange.Core#137]
### Lagrange项目

OneBot

### 新需求内容

希望可以配置容器数据文件的权限

如果用 1panel 来创建容器，Lagrange 的文件权限如下图

![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66513481/b96543aa-f4d1-487d-83af-cafcba1047e1)

非 root 权限运行的程序无法修改它们

**Comment by DarkCWK** [comment]
询问一下 gocqhttp 是怎么配置容器文件权限的

**Comment by A-kirami** [comment]
> 询问一下 gocqhttp 是怎么配置容器文件权限的

应该是这部分

https://github.com/Mrs4s/go-cqhttp/blob/master/Dockerfile#L32-L37

https://github.com/Mrs4s/go-cqhttp/blob/master/docker-entrypoint.sh#L15-L17

**Comment by DarkCWK** [comment]
> > 询问一下 gocqhttp 是怎么配置容器文件权限的
> 
> 应该是这部分
> 
> https://github.com/Mrs4s/go-cqhttp/blob/master/Dockerfile#L32-L37
> 
> https://github.com/Mrs4s/go-cqhttp/blob/master/docker-entrypoint.sh#L15-L17

是通过配置 ENV 中的 UID GID UMASK 进行配置么？

**Comment by DarkCWK** [comment]
> 应该是这部分
> 
> https://github.com/Mrs4s/go-cqhttp/blob/master/Dockerfile#L32-L37
> 
> https://github.com/Mrs4s/go-cqhttp/blob/master/docker-entrypoint.sh#L15-L17

看起来配置的方式应该是创建时注入需要的 UID, GID, UMASK 对么?

**Comment by A-kirami** [comment]
> > 应该是这部分
> > [Mrs4s/go-cqhttp@`master`/Dockerfile#L32-L37](https://github.com/Mrs4s/go-cqhttp/blob/master/Dockerfile?rgh-link-date=2024-03-05T17%3A28%3A43Z#L32-L37)
> > [Mrs4s/go-cqhttp@`master`/docker-entrypoint.sh#L15-L17](https://github.com/Mrs4s/go-cqhttp/blob/master/docker-entrypoint.sh?rgh-link-date=2024-03-05T17%3A28%3A43Z#L15-L17)
> 
> 看起来配置的方式应该是创建时注入需要的 UID, GID, UMASK 对么?

是的，指定环境变量

**Comment by ishkong** [comment]
https://github.com/LagrangeDev/Lagrange.Core/commit/5073ddf6658b9be5c27c9ee1c73eefae166ccc4d
