### ISSUE TITLE
[Bug?]: 好友邀请收到错误的多余报文

### ISSUE THREAD

**Issue by Xiangze-Li** [LagrangeDev/Lagrange.Core#141]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

46fc168

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

机器人验证方式选 验证消息, 向机器人发送好友请求.

### 期望的结果是什么？

WS 客户端收到 1 条正确报文

### 实际的结果是什么？

收到 2 条报文, 其中一条的 `user_id` 字段和 `self_id` 字段都是机器人的 QQ 号.

```
{"user_id":NOT_BOT,"request_type":"friend","comment":"","flag":"X","time":1709540095,"self_id":BOT,"post_type":"request"}

{"user_id":BOT,"request_type":"friend","comment":"","flag":"X","time":1709540104,"self_id":BOT,"post_type":"request"}
```

**Comment by Linwenxuan05** [comment]
Fixed at a961d856d8f24e87ee7974d714989dd8b71c6899
