### ISSUE TITLE
[Bug]: 当前 http 接口表现和 obv11 文档不一致

### ISSUE THREAD

**Issue by DarkCWK** [LagrangeDev/Lagrange.Core#149]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

be3141ff

### 运行环境

Windows

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

向配置好的服务器地址发送
```http
POST /send_group_msg HTTP/1.1
Host: http://localhost:10002
Content-Type: application/json

{
    "group_id": 0,
    "message": [
        {
            "type": "text",
            "data": {
                "text": "测试"
            }
        }
    ]
}
```
无法发送内容

### 期望的结果是什么？

成功发送消息

### 实际的结果是什么？

无法发送内容

### 日志记录（可选）

```log
info: Lagrange.OneBot.Core.Network.Service.HttpService[0]
      Receive(Conn: 9d8243dc-d4dd-417d-97b6-3fb570d6fe32: {"action":"","params":{
          "action": "send_group_msg",
          "params": {
              "group_id": 0,
              "message": [
                  {
                      "type": "text",
                      "data": {
                          "text": "测试"
                      }
                  }
              ]
          }
      }})
trce: Lagrange.OneBot.Core.Network.Service.HttpService[1]
      Send(Conn: 9d8243dc-d4dd-417d-97b6-3fb570d6fe32: {"status":"failed","retcode":404,"data":null,"echo":null})
```

### 补充说明（可选）

https://github.com/botuniverse/onebot-11/blob/master/communication/http.md#%E8%AF%B7%E6%B1%82

![图片](https://github.com/LagrangeDev/Lagrange.Core/assets/20531116/8a469d7f-7585-4960-9868-ee77789f32b2)

**Comment by ishkong** [comment]
https://github.com/LagrangeDev/Lagrange.Core/blob/be3141ff54960d0a2803b785a33195a1cbd6ceb2/Lagrange.OneBot/Core/Network/Service/HttpService.cs#L83-L115

是不是application/json忘记处理action了（
