### ISSUE TITLE
[Bug] get_group_member_info 中 sex 字段不正确

### ISSUE THREAD

**Issue by DarkCWK** [LagrangeDev/Lagrange.Core#152]
get_group_member_info响应的sex字段似乎是 '' 而不是 male 或 female 或 unknown

_Originally posted by @lava081 in https://github.com/LagrangeDev/Lagrange.Core/issues/48#issuecomment-1982160417_

**Comment by ishkong** [comment]
好像是nt协议的问题，暂时标记为`bug`和`wontfix`

**Comment by Linwenxuan05** [comment]
确实拿不到 没办法 必须要获取用户详细信息才能拿的到这个 开销太大了
