### ISSUE TITLE
[Feature Request]: 希望lagrange.core未来能够支持读取并发送本地图片

### ISSUE THREAD

**Issue by bugtower100** [LagrangeDev/Lagrange.Core#157]
### Lagrange项目

Core

### 新需求内容

现在在使用lagrange.core时发现发送图片只能利用cq码发送，但是cq码字段过长，在使用的时候过于冗长不方便，再加上本地图片过多，一个个更改起来很麻烦，不知道开发组未来有没有实现发送本地图片的计划

**Comment by CrackTC** [comment]
CQ码的解析逻辑在Lagrange.Onebot，而且Lagrange支持json消息段。

bugtower100 ***@***.***> 于2024年3月8日周五 16:58写道：

**Comment by DarkCWK** [comment]
目前单 `Lagrange.Core` 是连 `CQCode` 都没有支持的
而 `Lagrange.OneBot` 是支持 `array` 方式发送消息的, `CQCode` 支持反而比较弱
