### ISSUE TITLE
[Bug]: 私聊消息回复不完整

### ISSUE THREAD

**Issue by PhyX-Meow** [LagrangeDev/Lagrange.Core#158]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

6319cb3947d26fa59b962c9271133b32a67ad865

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

发送私聊回复消息

### 期望的结果是什么？

回复消息引用显示原消息的发送人和发送时间，如图
![02388ee4f4a81b2584156648c745e238](https://github.com/LagrangeDev/Lagrange.Core/assets/17513581/8ee70c38-2103-4853-9f02-d548537f5a83)

### 实际的结果是什么？

只有消息引用本身，如图
![3aaf41e8fc102c96fabb91e4bebe1943](https://github.com/LagrangeDev/Lagrange.Core/assets/17513581/424c56e3-22f0-4976-bd8b-cd993ddbbc5d)

**Comment by Linwenxuan05** [comment]
已经确认是Bug

**Comment by Linwenxuan05** [comment]
https://github.com/LagrangeDev/Lagrange.Core/commit/0705942e8e3a3ffe966121b6eade199bf0cde40a
