### ISSUE TITLE
[Feature Request]: 希望message可以提供string格式的数据

### ISSUE THREAD

**Issue by Blokura** [LagrangeDev/Lagrange.Core#160]
### Lagrange项目

OneBot

### 新需求内容

go-cqhttp的配置文件中message节点下可以设置post-format，可选项为string和array。
如果是string时，发送的数据中message与raw_message似乎是一样的。
提供string的话可以兼容使用了该特性的、支持go-cqhttp的项目和SDK接入。

**Comment by Linwenxuan05** [comment]
Fixed at https://github.com/LagrangeDev/Lagrange.Core/commit/13c8e2c0be50fc8b50bd0399bc9fb3e45c0d5690

**Comment by Blokura** [comment]
草，看起来string返回会把raw_message给去掉了？不麻烦的话请求保留一下，部分SDK对消息构造有要求，会报错缺少raw_message。
贴一个go-cqhttp的string消息：
`{'post_type': 'message', 'message_type': 'group', 'time': 1709964846, 'self_id': 114514, 'sub_type': 'normal', 'message_seq': 14997, 'raw_message': '[CQ:at,qq=114514] hello world!', 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Blokura', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 114514}, 'user_id': 114514, 'message_id': 370673629, 'font': 0, 'group_id': 114514, 'message': '[CQ:at,qq=114514] hello world!', 'anonymous': None}`
