### ISSUE TITLE
[Feature Request]: MessageSegment - Music

### ISSUE THREAD

**Issue by HornCopper** [LagrangeDev/Lagrange.Core#165]
### Lagrange项目

OneBot

### 新需求内容

希望支持Onebot的MessageSegment中的music，以便于音乐类程序的处理。

**Comment by HornCopper** [comment]
![81D6ED2748867BD54B9C20D4D220C48F](https://github.com/KonataDev/Lagrange.Core/assets/68726147/d801183c-7d3b-4071-9250-8af180116ea1)

**Comment by HornCopper** [comment]
![81D6ED2748867BD54B9C20D4D220C48F](https://github.com/KonataDev/Lagrange.Core/assets/68726147/d30eb7d4-cd4f-426c-adcd-37fad24c4304)

**Comment by scarletborder** [comment]
目前用第三方API签名的卡片，通过Onebot发json可以暂且实现
自己实现是否可以参考[here](https://github.com/Mrs4s/MiraiGo/pull/307)

**Comment by lngex** [comment]
> 目前用第三方API签名的卡片，通过Onebot发json可以暂且实现 自己实现是否可以参考[here](https://github.com/Mrs4s/MiraiGo/pull/307)

Lagrange不能直接发送json消息吗

**Comment by scarletborder** [comment]
> > 目前用第三方API签名的卡片，通过Onebot发json可以暂且实现 自己实现是否可以参考[here](https://github.com/Mrs4s/MiraiGo/pull/307)
> 
> Lagrange不能直接发送json消息吗

不能，这个需要QQ的签名，我见到的解决方案一个是逆向这方面的逻辑，这也是部分第三方API做的。另一个是使用QQ官方的Bot

**Comment by DarkCWK** [comment]
completed in https://github.com/LagrangeDev/Lagrange.Core/commit/9e9c5a6b93956ef79f696c7290ad8aeb54a79939
