### ISSUE TITLE
[Feature Request]: 发送 私聊 和 群聊Poke

### ISSUE THREAD

**Issue by ishkong** [LagrangeDev/Lagrange.Core#169]
### Lagrange项目

OneBot

### 新需求内容

原始poke为OneBotSegment
参数:

| 参数名 | 类型  | 说明         |
| ------ | ----- | ------------ |
| `qq`   | int | 需要戳的成员 |

**Comment by Linwenxuan05** [comment]
因为架构问题 做不到Segment Based的Poke
做成API了
