### ISSUE TITLE
[Feature Request]: Add Option for Sticker Sending in Image Messages

### ISSUE THREAD

**Issue by ghost** [LagrangeDev/Lagrange.Core#195]
### Lagrange项目

OneBot

### 新需求内容

Sending images directly may occupy a significant portion of the chat space. Sending thumbnails can reduce the space occupied.

**Comment by DarkCWK** [comment]
![31b463702d6fd2b69b3d3926f34d9e1d](https://github.com/KonataDev/Lagrange.Core/assets/20531116/2968b62a-688e-4005-9a95-05d6eb5547e3)
