### ISSUE TITLE
onebot报错：NetWorkError(message='Websocket call api send_msg timeout')

### ISSUE THREAD

**Issue by ReiRzior** [LagrangeDev/Lagrange.Core#24]
![image](https://github.com/Linwenxuan05/Lagrange.Core/assets/109207706/33530c99-da88-4358-b477-96393015d6c1)
似乎所有插件都这样

**Comment by ReiRzior** [comment]
已更新到最新版，大部分本地插件问题解决，不过所有使用api查询外部网站的插件都报该错误

**Comment by KelsAstell** [comment]
> 似乎所有插件都这样

如果是Onebot11的話，可以通過修改對應版本Python
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/33265134/b5d399e0-de6b-40cf-b4be-841b185bc601)
中`adapter.py`的`_call_api`函數第145行，讓它不拋出異常。
實際使用中建議在venv中操作，直接修改package可能會造成無法預計的後果。
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/33265134/9d818f79-19b9-4291-9ae4-3e5e800eccac)
**申明
我提供的信息僅供技術交流使用，並不構成任何個人最終立場或專業建議。使用這些信息所造成的任何後果和損失，我概不負責。在使用這些信息之前，請確保進行充分的研究、評估和驗證，並在必要時咨詢專業人士。任何基於這些信息做出的決策，都應由使用者自行承擔風險和責任。**
