### ISSUE TITLE
[Bug?]: 使用base64发送图片时，有概率上传失败，之后卡住消息发送队列

### ISSUE THREAD

**Issue by Lambholl** [LagrangeDev/Lagrange.Core#248]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

882e0b7

### 运行环境

Linux

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

使用base64向框架发送[CQ:image,file=base64://xxxxxxxxx]

### 期望的结果是什么？

成功发送图片

### 实际的结果是什么？

有概率上传成功，也有概率上传失败（原因未知），在上传后会进行重试，而貌似消息发送有队列机制，因此会卡住别的消息的发送，只有重启框架才能恢复正常
![image](https://github.com/KonataDev/Lagrange.Core/assets/55140169/0a1d58b8-ee85-4cd8-a9fe-c9a470bec9bd)

**Comment by Linwenxuan05** [comment]
拉格兰内部是事件系统实现没有消息队列 我觉得你可能触发了其他的Bug

**Comment by Lambholl** [comment]
> 拉格兰内部是事件系统实现没有消息队列 我觉得你可能触发了其他的Bug

从具体情况来看是类似队列，有文字和图片同时发送时，会因为图片上传失败，将文字不断地重复发送，而后续消息也没有发出去

**Comment by MX-fox** [comment]
发生类似bug，同时发送同一张本地图片，lagrange和电脑都提示文件被占用
![image](https://github.com/KonataDev/Lagrange.Core/assets/106176511/7f7f5b21-f790-4566-85e1-6e4f3eea1c10)
![image](https://github.com/KonataDev/Lagrange.Core/assets/106176511/b125ef20-4a08-45b5-978f-2f46154e65a3)
然后消息队列被卡住
当发送本地语音文件时也遇到同样情况
