### ISSUE TITLE
[Bug?]: 一次私聊戳一戳，将会产生两条 Poke 消息上报

### ISSUE THREAD

**Issue by aicorein** [LagrangeDev/Lagrange.Core#299]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

90545af52129be5e11118cc3c5f4eb5302db7127

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

任意触发一次私聊戳一戳。

### 期望的结果是什么？

只应该产生一次 Poke 消息上报。

### 实际的结果是什么？

以下为其他 bot 开发框架的日志记录。极短时间内接收到了两个上报，且这两个上报的数据完全一致：

![image](https://github.com/KonataDev/Lagrange.Core/assets/75575271/884b8155-00b5-41e6-8aca-631f5c2faeea)

使用其他 websocket 测试工具测试结果一致，不过记录较为简陋：

![image](https://github.com/KonataDev/Lagrange.Core/assets/75575271/1a1d0644-5b00-4873-bac1-c6cd7cea7309)

### 日志记录（可选）

```Shell
Lagrange 相关日志如下：

nfo: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [01:46:58] FriendPokeEvent: 1574260633
info: Lagrange.OneBot.Core.Notify.NotifyService[0]
      [01:46:58] FriendPokeEvent: 1574260633
```

**Comment by DarkCWK** [comment]
未能复现
使用 NTQQPC 的抖一抖和 Android 的戳一戳皆只有一条上报消息

**Comment by aicorein** [comment]
NTQQPC 我这边测试确实只有一条。
但是 Android 这边，在保证 lagrange 最新构建的情况下，我又测试了不同连接方式、重新登录、重启电脑、其他qq号登录 lagrange、不同运行平台（win, linux）、不同物理设备、其他qq号来戳一戳依然存在这个问题。还询问了两位也使用 lagrange 的朋友，同样存在此问题。
建议暂时不关闭此 issue，等一段时间看是否有类似情况。

**Comment by Vescrity** [comment]
```
info: Lagrange.OneBot.Core.Notify.NotifyService[0]     
      [15:39:57] FriendPokeEvent:  手动隐藏
info: Lagrange.OneBot.Core.Notify.NotifyService[0]     
      [15:39:57] FriendPokeEvent:  手动隐藏           
```
Lagrange: master 最新状态，构建指令
`dotnet publish -r linux-amd64 --self-contained -p:PublishSingleFile=True -p:DebugType=none -p:EnableCompressionInSingleFile=True -c Release --framework=net8.0 `
使用 Linux 协议。正向websocket, 一次私聊的戳一戳得到如上两条。接受端同样接受到两条上报。

**Comment by Simplxss** [comment]
这边测试也遇到了 暂时不确定问题来源 似乎tx下发了两次msgpush(或者误收了?)

**Comment by hfc0076** [comment]
我也遇到同样的情况，正向WebSocket，私聊戳一戳上报两条完全一样的消息

**Comment by aicorein** [comment]
> tx 发送了两次 Poke 消息

lgr 是否有修复的打算？还是说把去重任务转移给用户或下游框架进行？

**Comment by qllokirin** [comment]
同样的情况，ReverseWebSocket，Windows运行拉格朗，一次戳一戳但会收到两次poke

**Comment by qllokirin** [comment]
好消息，[最新的版本](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/10009402154)已经修复了

> tips: 不过最新版目前有 #448
