### ISSUE TITLE
[Feature Request]: 获取skey

### ISSUE THREAD

**Issue by areCodeOI** [LagrangeDev/Lagrange.Core#348]
### Lagrange项目

OneBot

### 新需求内容

我看到有getSkey的方法但是并没有写获取bot的skey的接口，希望做一个单独的获取skey的接口或者完善get_cookies接口的返回信息：uin=0000; skey=ssss; p_uin=0000;p_skey=pppp

**Comment by Linwenxuan04** [comment]
在get_credentials接口
