### ISSUE TITLE
[Bug?]: 群文件上传时指定的文件夹无效

### ISSUE THREAD

**Issue by sweetymajo** [LagrangeDev/Lagrange.Core#350]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

481d281

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

尝试使用[GroupFSUpload]这个API上传群文件到指定文件夹。
测试代码如下：
`context!.GroupFSUpload(groupUin, fileEntity, "test");`

### 期望的结果是什么？

文件上传到群文件的[test]目录下。

### 实际的结果是什么？

文件上传到了群文件的根目录下。

### 简单的复现代码/链接（可选）

```C#
`context!.GroupFSUpload(groupUin, fileEntity, "test");`
```

**Comment by Linwenxuan05** [comment]
文件夹需要使用文件夹ID进行上传 具体请使用对应的借口进行获取

**Comment by sweetymajo** [comment]
> 文件夹需要使用文件夹ID进行上传 具体请使用对应的借口进行获取

理解了，非常感谢。
