### ISSUE TITLE
[Bug?]: Termux proot ubuntu容器下无法成功检测端口占用

### ISSUE THREAD

**Issue by Miuzarte** [LagrangeDev/Lagrange.Core#358]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

1eaa20ff334c41c64caf1a161de2269244489875

### 运行环境

其它（请在下方说明）

### 运行架构

arm64

### 连接方式

HTTP

### 重现步骤

运行环境: Arm64 Termux Proot Ubuntu (buff是有点多)

~~config存在http端口时运行会报错 `Access to the path '/proc/net/tcp' is denied.`~~

启动时检测端口会报错 `Access to the path '/proc/net/tcp' is denied.`

但此时ws端口会正常开放，http端口不会

日志在下方

### 期望的结果是什么？

正常启用http端口

### 实际的结果是什么？

无法检测到端口号是否占用

### 简单的复现代码/链接（可选）

```C#
"Implementations": [
        {
            "Type": "ForwardWebSocket",
            "Host": "0.0.0.0",
            "Port": 8081,
            "HeartBeatInterval": 5000,
            "HeartBeatEnable": true,
            "AccessToken": ""
        },
        {
            "Type": "Http",
            "Host": "0.0.0.0",
            "Port": 8091,
            "AccessToken": ""
        }
    ]
```

### 日志记录（可选）

```Shell
warn: Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection[4]
      [LagrangeWebSvcCollection]: WebService start failed.
      System.Net.NetworkInformation.NetworkInformationException (13): An error was encountered while querying information from the operating system. ---> System.UnauthorizedAccessException: Access to the path '/proc/net/tcp' is denied.
       ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
         at System.IO.File.ReadAllText(String path, Encoding encoding)
         at System.Net.NetworkInformation.StringParsingHelpers.ReadAllText(String filePath)
         at System.Net.NetworkInformation.StringParsingHelpers.ReadAllText(String filePath)
         at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile)
         at Lagrange.OneBot.Core.Network.Service.HttpService.IsPortInUse(UInt32 port)
         at Lagrange.OneBot.Core.Network.Service.HttpService.ExecuteAsync(CancellationToken token)
         at Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection.StartAsync(CancellationToken cancellationToken)
```

**Comment by DarkCWK** [comment]
websocket 在绑定已经被占用的端口时没有提示仍旧正常运行是么？

**Comment by Miuzarte** [comment]
> websocket 在绑定已经被占用的端口时没有提示仍旧正常运行是么？

不

> websocket 在绑定已经被占用的端口时没有提示仍旧正常运行是么？

哦确实是，才注意到只开了ws也报了

**Comment by DarkCWK** [comment]
> 另外还有个关不掉的问题，开了trace结果如图，直到我手动kill -9才结束
>
> 如果是环境的锅就不管了

另外提一个 issue 吧

**Comment by Miuzarte** [comment]
这个issue重新开还是？

**Comment by DarkCWK** [comment]
这里还有什么问题么

**Comment by Miuzarte** [comment]
> 这里还有什么问题么

上面说的，端口占用检测出错，ws正常监听，http没有

**Comment by DarkCWK** [comment]
被占用端口后无法正常监听啊

**Comment by Miuzarte** [comment]
> 被占用端口后无法正常监听啊

这两个端口都是没被占用的，但是因为检测不到占用情况，只有ws是继续监听了，可以的话希望http也能直接尝试监听吧
```
    "Implementations": [
        {
            "Type": "ForwardWebSocket",
            "Host": "0.0.0.0",
            "Port": 8081,
            "HeartBeatInterval": 5000,
            "HeartBeatEnable": true,
            "AccessToken": ""
        },
        {
            "Type": "Http",
            "Host": "0.0.0.0",
            "Port": 8091,
            "AccessToken": ""
        }
    ]
```
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/ce6457d3-b0b8-4812-8a86-6eae3e805bf7)
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/69ac0ffb-631d-4737-ba09-f4ac9635230a)

**Comment by DarkCWK** [comment]
只有 ws 的时候也提示占用了?

**Comment by Miuzarte** [comment]
> 只有 ws 的时候也提示占用了?

给我一拳，我记得前面删掉了http启动还是报了`Access to the path '/proc/net/tcp' is denied.`

刚刚试了下没报...

**Comment by DarkCWK** [comment]
> > 只有 ws 的时候也提示占用了?
> 
> 给我一拳，我记得前面删掉了http启动还是报了`Access to the path '/proc/net/tcp' is denied.`
> 
> 刚刚试了下没报...

那么只有 http 的时候报错了吗

我看你的图提示的是拒绝连接, 很有可能 8091 是被占用了的

建议先用 `ss` 等命令检查一下端口占用情况

**Comment by Miuzarte** [comment]
> > > 只有 ws 的时候也提示占用了?
> > 
> > 
> > 给我一拳，我记得前面删掉了http启动还是报了`Access to the path '/proc/net/tcp' is denied.`
> > 刚刚试了下没报...
> 
> 那么只有 http 的时候报错了吗
> 
> 我看你的图提示的是拒绝连接, 很有可能 8091 是被占用了的
> 
> 建议先用 `ss` 等命令检查一下端口占用情况

没东西的端口都是拒绝连接

完全确定是没占用的，换过了好几个端口

![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/942b9f0f-28cd-441a-b6af-9317a01f0351)

只有http的时候也是报同样的错误

**Comment by DarkCWK** [comment]
关于 HTTP 我不是很熟悉
@CrackTC 问问这位大佬

**Comment by initialencounter** [comment]
@Miuzarte 看看你的 proot 怎么挂载文件的

**Comment by CrackTC** [comment]
https://github.com/LagrangeDev/Lagrange.Core/blob/8f8de88ffe3d84d16a6aa123b4af41a5e63db50d/Lagrange.OneBot/Core/Network/Service/HttpService.cs#L197
这里检测端口是否被占用会访问`/proc/net/tcp`,一般来说这个文件是所有用户可读的,不太清楚proot下是啥情况

**Comment by Miuzarte** [comment]
> @Miuzarte 看看你的 proot 怎么挂载文件的

用的是这个 https://github.com/termux/proot-distro
这方面不太懂，抱歉

**Comment by ishkong** [comment]
Android 13?

**Comment by Miuzarte** [comment]
> Android 13?

14

**Comment by ishkong** [comment]
有root吗？有root尝试禁用selinux

> > Android 13?
> 
> 14

**Comment by DarkCWK** [comment]
> 有root吗？有root尝试禁用selinux
> 
> > > Android 13?
> > 
> > 
> > 14

即便这是个解决方案我也认为直接去掉检测会比较好
selinux 绝对不应该被禁用

**Comment by Miuzarte** [comment]
> 有root吗？有root尝试禁用selinux
> 
> > > Android 13?
> > 
> > 
> > 14

确实可以

**Comment by DarkCWK** [comment]
> 确实可以

注意，即便可以也不建议禁用 selinux 运行
这非常的不安全

**Comment by Miuzarte** [comment]
> > 确实可以
> 
> 注意，即便可以也不建议禁用 selinux 运行 这非常的不安全

了解的，单纯做一下验证
