### ISSUE TITLE
[Bug?]: 存在未断开的websocket连接时无法成功退出

### ISSUE THREAD

**Issue by Miuzarte** [LagrangeDev/Lagrange.Core#360]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

1eaa20ff334c41c64caf1a161de2269244489875

### 运行环境

Windows, Andorid Termux

### 运行架构

x86, arm64

### 连接方式

正向 WebSocket

### 重现步骤

开放websocket端口并让机器人连接，此时发送`Ctrl+C`无法退出lagrange

![ed1b1d2db7565dad924549b3e65fc22c](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/c13f9ad9-ba44-46b6-ad68-cd5a78900998)

此时让机器人断开ws连接则会解除冻结，程序退出

![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/c6ce01d3-4e36-4a8b-9210-6d4c297e3279)

### 期望的结果是什么？

停止运行时自动断开所有ws连接成功退出

### 实际的结果是什么？

存在ws连接时需要`kill -9`或者手动关闭所有机器人

### 补充说明（可选）

退出时ws连接已经为EOF状态
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/3365c593-08c9-42b7-b204-4a57808813e5)

**Comment by DarkCWK** [comment]
> 本来在试windows的，但我Windows上websocket和http都跑不起来，管理员权限

Windows 下微软似乎对绑定的端口进行了限制，你可以绑定到 127.0.0.1 测试，这个不需要管理员权限

**Comment by DarkCWK** [comment]
目前 Windows 没有复现, 可否提供更详细的过程

**Comment by DarkCWK** [comment]
例如 `ws_test.go` 的相关代码?

**Comment by Miuzarte** [comment]
> 目前 Windows 没有复现, 可否提供更详细的过程

`ws_test.go` 中会在10s后主动断开ws

10s之内发送Ctrl + C给lagrange无法退出，直到ws断开

https://github.com/LagrangeDev/Lagrange.Core/assets/66856838/4584f0ab-800b-4dd9-9a62-ae0b8aaf3172

**Comment by DarkCWK** [comment]
> > 目前 Windows 没有复现, 可否提供更详细的过程
> 
> `ws_test.go` 中会在10s后主动断开ws
> 
> 10s之内发送Ctrl + C给lagrange无法退出，直到ws断开
> 
>  2024-05-11_13-36-59_2560x1440@60.mp4

你的代码没有在收到 close 消息后按照正常流程回复 close

由于我的失误，没有在 Close 时添加超时处理，导致无法停止

**Comment by Miuzarte** [comment]
> > > 目前 Windows 没有复现, 可否提供更详细的过程
> > 
> > 
> > `ws_test.go` 中会在10s后主动断开ws
> > 10s之内发送Ctrl + C给lagrange无法退出，直到ws断开
> > 2024-05-11_13-36-59_2560x1440@60.mp4
> 
> 你的代码没有在收到 close 消息后按照正常流程回复 close
> 
> 由于我的失误，没有在 Close 时添加超时处理，导致无法停止

了解了，我的锅，抱歉🙏🙏🙏
