### ISSUE TITLE
[Feature Request]: 有没有发送视频的api,我目前是通过群文件和私聊文件的方式进行发送

### ISSUE THREAD

**Issue by cfwasd** [LagrangeDev/Lagrange.Core#368]
### Lagrange项目

OneBot

### 新需求内容

有没有发送视频的api,我目前是通过群文件和私聊文件的方式进行发送

**Comment by pk5ls20** [comment]
https://github.com/LagrangeDev/Lagrange.Core/commit/7ac856b5e73a1a7a296438593cda280038c1e2d9 后已实现
