### ISSUE TITLE
[Bug?]: 无法正常启动Lagrange.OneBot_linux-x64_8.0，卡在Signature Service is successfully established

### ISSUE THREAD

**Issue by WhyPilotXia** [LagrangeDev/Lagrange.Core#372]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

Lagrange.OneBot_linux-x64_8.0.zip

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

打开https://aistudio.baidu.com/projectdetail/7882951启动项目，进入控制台，按照文档准备好相关文件，运行：
./Lagrange.OneBot
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/86997355/71e05bb4-11d8-487b-9889-ce5f701aca32)

### 期望的结果是什么？

能正常启动程序

### 实际的结果是什么？

直接启动，无法扫码登录，提示：
[WtExchangeLogic] [INFORMATION]: Connecting Servers...
Unhandled exception. System.PlatformNotSupportedException: The system's ping utility could not be found.
   at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal[TArg](TArg getAddressArg, Func`3 getAddress, Int32 timeout, Byte[] buffer, PingOptions options, CancellationToken cancellationToken)
   at Lagrange.Core.Utility.Network.Icmp.PingAsync(Uri hostIp, Int32 timeout)
   at Lagrange.Core.Internal.Context.SocketContext.OptimumServer(Boolean requestMsf, Boolean useIPv6Network)
   at Lagrange.Core.Internal.Context.SocketContext.Connect()
   at Lagrange.Core.Internal.Context.Logic.Implementation.WtExchangeLogic.FetchQrCode()
   at Lagrange.OneBot.LagrangeApp.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Lagrange.OneBot.Program.Main(String[] args)
Aborted (core dumped)

看到是由于系统不支持ping
于是本地登好再将
```
appsettings.json
device.json
keystore.json
```
拷入，运行后成功打开：

aistudio@jupyter-3211270-7882951:~/publish$ ./Lagrange.OneBot
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/aistudio/publish
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: Lagrange.OneBot.LagrangeApp[0]
      Lagrange.OneBot Implementation has started
info: Lagrange.OneBot.LagrangeApp[0]
      Protocol:  | 3.1.2-13107
info: Lagrange.OneBot.Utility.OneBotSigner[0]
      Signature Service is successfully established
 但是始终卡在这，再也没有进一步的消息了，也没有反应。

### 简单的复现代码/链接（可选）

```C#
https://aistudio.baidu.com/projectdetail/7882951
```

### 日志记录（可选）

```Shell
直接启动，无法扫码登录，提示：
[WtExchangeLogic] [INFORMATION]: Connecting Servers...
Unhandled exception. System.PlatformNotSupportedException: The system's ping utility could not be found.
   at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingAsyncInternal[TArg](TArg getAddressArg, Func`3 getAddress, Int32 timeout, Byte[] buffer, PingOptions options, CancellationToken cancellationToken)
   at Lagrange.Core.Utility.Network.Icmp.PingAsync(Uri hostIp, Int32 timeout)
   at Lagrange.Core.Internal.Context.SocketContext.OptimumServer(Boolean requestMsf, Boolean useIPv6Network)
   at Lagrange.Core.Internal.Context.SocketContext.Connect()
   at Lagrange.Core.Internal.Context.Logic.Implementation.WtExchangeLogic.FetchQrCode()
   at Lagrange.OneBot.LagrangeApp.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Lagrange.OneBot.Program.Main(String[] args)
Aborted (core dumped)

看到是由于系统不支持ping
于是本地登好再将

appsettings.json
device.json
keystore.json
```
拷入，运行后成功打开：

aistudio@jupyter-3211270-7882951:~/publish$ ./Lagrange.OneBot
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/aistudio/publish
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: Lagrange.OneBot.LagrangeApp[0]
      Lagrange.OneBot Implementation has started
info: Lagrange.OneBot.LagrangeApp[0]
      Protocol:  | 3.1.2-13107
info: Lagrange.OneBot.Utility.OneBotSigner[0]
      Signature Service is successfully established
 但是始终卡在这，再也没有进一步的消息了，也没有反应。
```


### 补充说明（可选）

_No response_

**Comment by DarkCWK** [comment]
怀疑是无法连接到签名服务器, 请检查 ipv6 (`curl -iv https://v4.ident.me/`) 和 ipv4 (`curl -iv https://v4.ident.me/`) 是否畅通

再检查是否可以连接到签名服务器 https://sign.lagrangecore.org/api/sign (`curl -iv https://sign.lagrangecore.org/api/sign`)

以上操作请在启动 `Lagrange.OneBot` 的机器运行

**Comment by DarkCWK** [comment]
不好意思，以上 ipv6 的命令写错了

**Comment by WhyPilotXia** [comment]
> 怀疑是无法连接到签名服务器, 请检查 ipv6 (`curl -iv https://v4.ident.me/`) 和 ipv4 (`curl -iv https://v4.ident.me/`) 是否畅通
> 
> 再检查是否可以连接到签名服务器 https://sign.lagrangecore.org/api/sign (`curl -iv https://sign.lagrangecore.org/api/sign`)
> 
> 以上操作请在启动 `Lagrange.OneBot` 的机器运行
```shell
aistudio@jupyter-3211270-7882951:~/publish$ curl -iv https://v4.ident.me/
*   Trying 49.12.234.183...
* Connected to v4.ident.me (49.12.234.183) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: any.ident.me (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=any.ident.me
*        start date: Wed, 10 Apr 2024 10:05:59 GMT
*        expire date: Tue, 09 Jul 2024 10:05:58 GMT
*        issuer: C=US,O=Let's Encrypt,CN=R3
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: v4.ident.me
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: nginx
Server: nginx
< Date: Tue, 14 May 2024 14:56:27 GMT
Date: Tue, 14 May 2024 14:56:27 GMT
< Content-Type: text/plain
Content-Type: text/plain
< Content-Length: 14
Content-Length: 14
< Connection: keep-alive
Connection: keep-alive
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Cache-Control: no-cache, no-store, must-revalidate
Cache-Control: no-cache, no-store, must-revalidate

< 
* Connection #0 to host v4.ident.me left intact
106.12.204.140
``` 
```shell
aistudio@jupyter-3211270-7882951:~/publish$ curl -iv https://v6.ident.me/
*   Trying 2a01:4f8:c0c:bd0a::1...
* Immediate connect fail for 2a01:4f8:c0c:bd0a::1: Cannot assign requested address
* Closing connection 0
curl: (7) Couldn't connect to server
``` 
```shell
aistudio@jupyter-3211270-7882951:~/publish$ curl -iv https://sign.lagrangecore.org/api/sign
*   Trying 104.21.51.166...
* Connected to sign.lagrangecore.org (104.21.51.166) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by DarkCWK** [comment]
> 打开[https://aistudio.baidu.com/projectdetail/7882951启动项目，进入控制台，按照文档准备好相关文件，运行：](https://aistudio.baidu.com/projectdetail/7882951%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE%EF%BC%8C%E8%BF%9B%E5%85%A5%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%8C%E6%8C%89%E7%85%A7%E6%96%87%E6%A1%A3%E5%87%86%E5%A4%87%E5%A5%BD%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6%EF%BC%8C%E8%BF%90%E8%A1%8C%EF%BC%9A)

注意, 你的 `keystore.json` 被你公布在网上, 其中 `keystore.json` 包含了账号的认证信息, 其他使用 `Lagrange` 的人可以通过伪装登陆你的账号!

**Comment by WhyPilotXia** [comment]
> > 打开[https://aistudio.baidu.com/projectdetail/7882951启动项目，进入控制台，按照文档准备好相关文件，运行：](https://aistudio.baidu.com/projectdetail/7882951%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE%EF%BC%8C%E8%BF%9B%E5%85%A5%E6%8E%A7%E5%88%B6%E5%8F%B0%EF%BC%8C%E6%8C%89%E7%85%A7%E6%96%87%E6%A1%A3%E5%87%86%E5%A4%87%E5%A5%BD%E7%9B%B8%E5%85%B3%E6%96%87%E4%BB%B6%EF%BC%8C%E8%BF%90%E8%A1%8C%EF%BC%9A)
> 
> 注意, 你的 `keystore.json` 被你公布在网上, 其中 `keystore.json` 包含了账号的认证信息, 其他使用 `Lagrange` 的人可以通过伪装登陆你的账号!

收到，我取消允许该设备应该可以了

**Comment by WhyPilotXia** [comment]
新信息：发现在删除设备后的现象和之前完全一样，都是到这就不动了，也没有报错，也就是说可能并没有到登录，未使用keystore.json：
```shell
aistudio@jupyter-3211270-7882951:~$ cd ./publish/
aistudio@jupyter-3211270-7882951:~/publish$ ls
appsettings.json  device.json  keystore.json  lagrange-0.db  Lagrange.OneBot
aistudio@jupyter-3211270-7882951:~/publish$ ./Lagrange.OneBot
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/aistudio/publish
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: Lagrange.OneBot.LagrangeApp[0]
      Lagrange.OneBot Implementation has started
info: Lagrange.OneBot.LagrangeApp[0]
      Protocol:  | 3.1.2-13107
info: Lagrange.OneBot.Utility.OneBotSigner[0]
      Signature Service is successfully established
```

**Comment by DarkCWK** [comment]
你给系统安装一个 ping 工具试试

**Comment by WhyPilotXia** [comment]
不给安装...这个系统有限制



---Original---
From: ***@***.***&gt;
Sent at: 2024年6月14日(Fri) Evening6:27
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LagrangeDev/Lagrange.Core] [Bug?]: 无法正常启动Lagrange.OneBot_linux-x64_8.0，卡在Signature Service is successfully established (Issue #372)




 
你给系统安装一个 ping 工具试试

**Comment by nidbCN** [comment]
我在 docker 镜像 ` mcr.microsoft.com/dotnet/runtime:8.0-bookworm-slim` 所构建的容器中遇到了同样问题。

但切换至 root 可以正常使用。
