### ISSUE TITLE
[Feature Request]: 可以加入CORS策略吗

### ISSUE THREAD

**Issue by jinyu2022** [LagrangeDev/Lagrange.Core#379]
### Lagrange项目

Core

### 新需求内容

可以加入CORS策略吗

**Comment by CrackTC** [comment]
要加感觉只能在存在`AccessToken`的情况下加，不然可能会被csrf

**Comment by CrackTC** [comment]
是想做webui嘛，感觉应用场景不是很广，建议还是自己fork下加上吧
