### ISSUE TITLE
[Feature Request]: 希望实现音乐分享功能

### ISSUE THREAD

**Issue by SanaeMio** [LagrangeDev/Lagrange.Core#382]
### Lagrange项目

OneBot

### 新需求内容

希望实现Lagrange.OneBot的Message Segement中的Music功能，以方便对接机器人的点歌功能，谢谢！

**Comment by MerlinCN** [comment]
+1

**Comment by findingwch** [comment]
+1

**Comment by sisi0318** [comment]
b77_9包被定死appid了 所以有一点点麻烦

**Comment by sisi0318** [comment]
> b77_9包被定死appid了 所以有一点点麻烦

https://github.com/LagrangeDev/Lagrange.Core/actions/runs/9344833610 已新增自定义音乐卡片签名api配置

**Comment by SanaeMio** [comment]
> > b77_9包被定死appid了 所以有一点点麻烦
> 
> https://github.com/LagrangeDev/Lagrange.Core/actions/runs/9344833610 已新增自定义音乐卡片签名api配置

感谢，不过刚才我在WIN10上试了下Lagrange.OneBot_win-x64_8.0的包，启动程序就会闪退。。

**Comment by MerlinCN** [comment]
MusicSignServerUrl这个要怎么搭建？

**Comment by sisi0318** [comment]
> MusicSignServerUrl这个要怎么搭建？

目前实现原理均为手q协议代为签名后进行转发

**Comment by sisi0318** [comment]
> > MusicSignServerUrl这个要怎么搭建？
> 
> 目前实现原理均为手q协议代为签名后进行转发

在q群有搭建好的

**Comment by RTAkland** [comment]
> > > MusicSignServerUrl这个要怎么搭建？
> > 
> > 
> > 目前实现原理均为手q协议代为签名后进行转发
> 
> 在q群有搭建好的

请问qq群在哪里呢，能提供一下qq群号吗? pls
