### ISSUE TITLE
[Bug?]: 第一次使用 出现了错误

### ISSUE THREAD

**Issue by yuzhangkaii** [LagrangeDev/Lagrange.Core#385]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

none

### 运行环境

Linux

### 运行架构

arm

### 连接方式

正向 WebSocket

### 重现步骤

./Lagrange.OneBot
![Screenshot_2024-05-29-22-50-05-16_3d419158bad5872c40592a6c9956e692](https://github.com/LagrangeDev/Lagrange.Core/assets/53356318/23f3ab95-5725-40f9-9a2a-ec62d4f97e1b)

### 期望的结果是什么？

可以正常运行

### 实际的结果是什么？

出现了错误 ，但是不知道怎么解决

**Comment by DarkCWK** [comment]
根据日志应该是无法连接到腾讯的服务器, 检查一下网络连接

**Comment by ishkong** [comment]
长时间未回复，视为已解决，关闭issue，还有问题请再次开启
