### ISSUE TITLE
[Feature Request]: 文件路径有空格 会报找不到文件

### ISSUE THREAD

**Issue by kkgg0521** [LagrangeDev/Lagrange.Core#387]
### Lagrange项目

Core

### 新需求内容

s

**Comment by kkgg0521** [comment]
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/59002786/eafc406a-bde4-411e-a331-9437172d8289)

**Comment by DarkCWK** [comment]
这个是 bug！请使用[错误报告](https://github.com/LagrangeDev/Lagrange.Core/issues/new?projects=&template=bug-report.yml)模版提出 issue
