### ISSUE TITLE
[Feature Request]: 接收图片消息 多返回一个文件名字段filename

### ISSUE THREAD

**Issue by Hanserprpr** [LagrangeDev/Lagrange.Core#398]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/bc64afe999752b93abc1340a2486d0134277c439

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

print(MessageEvent)

### 期望的结果是什么？

[image:file=filename,url=url,summary=[图片]]

### 实际的结果是什么？

[image:file=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyMDQx...,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyMDQx...,summary=[图片]]

**Comment by ishkong** [comment]
emmm，在tg群里看到了有人提到这个issue，回复一下

目前的行为符合ob11标准

https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/message/segment.md?plain=1#L93

`file` 参数应支持使用收到的图片文件名直接发送

应考虑改为一个feature request来返回时多返回filename字段
