### ISSUE TITLE
OneBot V12标准支持 | OneBot V12 support

### ISSUE THREAD

**Issue by littlekan233** [LagrangeDev/Lagrange.Core#413]
### Lagrange项目

OneBot

### 新需求内容

如题，请问开发者们有计划支持[OneBot V12标准](https://12.onebot.dev)吗？

**Comment by kenichiLyon** [comment]
目前obv12似乎还是草案而非确认发布的情况，现在适配似乎有些为时过早？
（叠甲：本人仅作为用户身份，站在contributor立场进行发言，不代表任何Lagrange组织内参与开发的开发者）
