### ISSUE TITLE
[Feature Request]: 建议增加入群审核功能

### ISSUE THREAD

**Issue by shaoxiu** [LagrangeDev/Lagrange.Core#431]
### Lagrange项目

OneBot

### 新需求内容

在bot有管理时，希望能够接收加群事件，方便对接ob11已有的处理加群请求功能。

目前已实现关键信息自动审批入群插件，但因为事件缺失无法工作。

**Comment by ishkong** [comment]
？经测试lgr会上报主动申请入群事件，以下是使用nonebot测试的日志，请检查你使用ob11端是否支持相关操作
07-23 17:52:27 [SUCCESS] nonebot | OneBot V11 *| [request.group.add]: {'time': 1721728347, 'self_id': *, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'add', 'group_id': *, 'user_id': *, 'flag': '*-*', 'comment': None, 'invitor_id': 0}
