### ISSUE TITLE
[Feature Request]: 好友分组信息

### ISSUE THREAD

**Issue by Stapxs** [LagrangeDev/Lagrange.Core#435]
### Lagrange项目

OneBot

### 新需求内容

-> https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/issues/100

之前找 lwx 说要做的
现在不干了不知道啥情况 XD

遇到了相关的 issue 所以问问情况（发出了关心的声音）
功能不刚需不做也无所谓.png

> 好友分组信息
用于获取好友的分组信息（包含特别关系分组）

**Comment by Linwenxuan04** [comment]
Implemented 7f67ae9377b4075ddb75505257fc55f85dbad54c
