### ISSUE TITLE
扫码登录失败，提示禁示登录。 手机上已同意

### ISSUE THREAD

**Issue by keyihen2** [LagrangeDev/Lagrange.Core#437]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

最新版

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

![1](https://github.com/LagrangeDev/Lagrange.Core/assets/25970458/7df58bc2-ec99-453a-b109-d4a89c6c7bc7)
扫码登录失败，提示禁示登录。 手机上已同意.
这个有办法解决吗

### 期望的结果是什么？

扫码登录失败，提示禁示登录。 手机上已同意.
这个有办法解决吗
![1](https://github.com/LagrangeDev/Lagrange.Core/assets/25970458/f15b15f1-6c16-49f3-ba9e-a709f419a21f)

### 实际的结果是什么？

扫码登录失败，提示禁示登录。 手机上已同意.
这个有办法解决吗
![1](https://github.com/LagrangeDev/Lagrange.Core/assets/25970458/f15b15f1-6c16-49f3-ba9e-a709f419a21f)

**Comment by DarkCWK** [comment]
# 请给出完整 Trace 日志!

检查你与签名服务器的链接

**Comment by 1052915220** [comment]
![image](https://github.com/LagrangeDev/Lagrange.Core/assets/110186678/2b78044c-8891-4839-86a6-ef4fa3973f4b)
修改配置，添加签名配置
`"SignServerUrl": "https://sign.lagrangecore.org/api/sign"`

**Comment by keyihen2** [comment]
> # 给出完整的Trace日志！
> 检查你与签名服务器的链接

配置没动过，莫名奇妙的就可以登录了

**Comment by keyihen2** [comment]
> ![图像](https://private-user-images.githubusercontent.com/110186678/347417184-2b78044c-8891-4839-86a6-ef4fa3973f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTg0NzYsIm5iZiI6MTcyMDYxODE3NiwicGF0aCI6Ii8xMTAxODY2NzgvMzQ3NDE3MTg0LTJiNzgwNDRjLTg4OTEtNDgzOS04NmE2LWVmNGZhMzk3M2Y0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMzI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzY4ZjU3OTA2MDYyZGE3NDBkNzA0NjY2N2YwY2Y5NTZhMTdlODdhNmRkZDNkNTE1ZDVhZGIyYzZkMjA1ZDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N3hgNylW12t9JGymZyRxQiBwhhST5wiaBL3psZvy_os) 修改配置，添加姓名配置 `"SignServerUrl": "https://sign.lagrangecore.org/api/sign"`

> # 给出完整的Trace日志！
> 检查你与签名服务器的链接

配置没动过，莫名奇妙的就可以登录了
