### ISSUE TITLE
[Bug?]: 新版本无法接收到图片消息

### ISSUE THREAD

**Issue by Yuelioi** [LagrangeDev/Lagrange.Core#448]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

最新版 f63e1b1

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

正常更新拉个狼 其他没有动

### 期望的结果是什么？

想使用新的戳一戳功能

### 实际的结果是什么？

无法获得图片消息 只有text了,  戳一戳是可以的

包括 NB日志看不到, 接受事件看不到, 拉个狼后台也看不到, 很多和图片相关的指令全部失效了

### 简单的复现代码/链接（可选）

```C#
@event_preprocessor
async def _(bot: Bot, event: MessageEvent, state: T_State):

    imgs = []
    ats = []

    msgs = event.get_message()
    print(event)
    print(msgs)

    event_dict = {"message_id": event.message_id}
    dict_ = await bot.call_api("get_msg", **event_dict)
    print(dict_)

    for seg in msgs:
        print(seg.type)
```
```


### Trace 级别日志记录（可选）

_No response_

### 补充说明（可选）

_No response_

**Comment by sisi0318** [comment]
新协议的图片的位置变了，等待修复
