### ISSUE TITLE
Login Failed: 140022017 | 登录失败: 当前版本仅限内部体验使用，敬请期待！

### ISSUE THREAD

**Issue by tong-ge** [LagrangeDev/Lagrange.Core#45]

**Comment by Linwenxuan05** [comment]
请使用Linux版本协议

**Comment by tong-ge** [comment]
fail: Lagrange.OneBot.LagrangeApp[0]
      [2023-11-26 11:30:00] [WtExchangeLogic] [FATAL]: Login failed: 45
fail: Lagrange.OneBot.LagrangeApp[0]
      [2023-11-26 11:30:00] [WtExchangeLogic] [FATAL]: Tag: 禁止登录

**Comment by xiaojun1998** [comment]
> 请加入tg群配置sign

群号多少啊

**Comment by Linwenxuan05** [comment]
见README

xiaojun1998 ***@***.***>于2023年12月15日 周五上午9:38写道：

**Comment by yst-one** [comment]
ss
