### ISSUE TITLE
[Bug?]: 使用二维码登录 二维码超时的问题

### ISSUE THREAD

**Issue by NoNameGMM** [LagrangeDev/Lagrange.Core#452]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

commit-681ceb6

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

```
while(true) {
    var qrCode = await bot.FetchQrCode();
    if (qrCode != null){
       await File.WriteAllBytesAsync("data/qrcode.png", qrCode.Value.QrCode);
       await bot.LoginByQrCode();
    }
}
```

### 期望的结果是什么？

在二维码120秒超时后能够重新加载一个二维码，并能成功登陆

### 实际的结果是什么？

120秒到了之后重新获取二维码 
提示：[WtExchangeLogic] [INFORMATION]: QrCode Fetched, Expiration: 120 seconds

**Comment by DarkCWK** [comment]
LoginByQrCode 内部会循环获取状态，你不需要自行循环获取

**Comment by NoNameGMM** [comment]
LoginByQrCode会在120秒后结束，然后进程就直接退出了
我也不是很理解为什么

**Comment by Linwenxuan04** [comment]
你说的这个应该算是一个feature request而不是Bug 因为在之前的go-cqhttp或者mirai中 二维码过期都是会直接导致程序退出的
