### ISSUE TITLE
[Bug?]: 使用send_group_msg发送at消息报错

### ISSUE THREAD

**Issue by mengluo04** [LagrangeDev/Lagrange.Core#454]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

ef6b41b

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

使用bot.call_api("send_group_msg", group_id=event.group_id,message={"type": "at", "data": {"qq": event.user_id}})发送艾特消息

### 期望的结果是什么？

正确发送at消息

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/f79e75a8-f1c4-40af-b109-c6213b32fdad)

**Comment by ishkong** [comment]
你拿着一个nonebot的log来问lgr发送报错，你的lgr日志呢？

**Comment by mengluo04** [comment]
> 你拿着一个nonebot的log来问lgr发送报错，你的lgr日志呢？
抱歉，这是lgr的日志
![image](https://github.com/user-attachments/assets/51fc16cb-a763-46d2-86f4-acf77197af7b)

**Comment by ishkong** [comment]
插件有问题，请参考onebot 11标准

https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E6%9F%90%E4%BA%BA

at的人的qq号是string字符串

**Comment by mengluo04** [comment]
> 插件有问题，请参考onebot 11标准
> 
> https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E6%9F%90%E4%BA%BA
> 
> at的人的qq号是string字符串

好的，谢谢
