### ISSUE TITLE
[Feature Request]: A function to get one's QID

### ISSUE THREAD

**Issue by Yuisyuu** [LagrangeDev/Lagrange.Core#455]
### Lagrange项目

Core

### 新需求内容

A function to get one's QID
like `userInfo.Qid`

**Comment by DarkCWK** [comment]
[BotFriend.cs#L26](https://github.com/LagrangeDev/Lagrange.Core/blob/681ceb6f8142a2e9f52162236367a43ffc82d16a/Lagrange.Core/Common/Entity/BotFriend.cs#L26) is the one you want.

You can get the `BotFriend` via `[OperationExt.cs#L15](https://github.com/LagrangeDev/Lagrange.Core/blob/681ceb6f8142a2e9f52162236367a43ffc82d16a/Lagrange.Core/Common/Interface/Api/OperationExt.cs#L15)` i.e. `BotContext.FetchFriends`.

**Comment by Yuisyuu** [comment]
> [BotFriend.cs#L26](https://github.com/LagrangeDev/Lagrange.Core/blob/681ceb6f8142a2e9f52162236367a43ffc82d16a/Lagrange.Core/Common/Entity/BotFriend.cs#L26) is the one you want.
> 
> You can get the `BotFriend` via [OperationExt.cs#L15](https://github.com/LagrangeDev/Lagrange.Core/blob/681ceb6f8142a2e9f52162236367a43ffc82d16a/Lagrange.Core/Common/Interface/Api/OperationExt.cs#L15) i.e. `BotContext.FetchFriends`.

it is not QQ user ID, it is this
![IMG_1723](https://github.com/user-attachments/assets/05c77b3f-85a0-4a65-a9f8-bce0737c22e0)
