### ISSUE TITLE
[Bug?]: 消息偶尔会发不出去

### ISSUE THREAD

**Issue by sweetymajo** [LagrangeDev/Lagrange.Core#458]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/b9aa91fa96c9ddf7e22cffdbc1506b0ccd6d3fd6

### 运行环境

Linux

### 运行架构

x64

### 连接方式

None

### 重现步骤

我建立了最小再现模型，就是在提供的Test示例基础上，添加了监听OnGroupMessageReceived的代码，根据关键词来回复测试文本。

### 期望的结果是什么？

可以正常回复测试文本。

### 实际的结果是什么？

大部分时候是有效的，偶尔出现消息发送不出去的情况。
控制台会出现Unsupported SSOFrame Received: MsgPush.PushGroupMsg这个内容。

### 补充说明（可选）

1.与[426](https://github.com/LagrangeDev/Lagrange.Core/issues/426)和[457](https://github.com/LagrangeDev/Lagrange.Core/issues/457)应该是相同的问题，之所以选择单独开issue是应426提交者的要求。也为了表明这个问题与OneBot无关，是Core的问题。
2.在windows(win10 x64)和linux(centos7 x64)下都出现，我个人经过数天的统计，win环境下出现问题的概率更高。
3.这个问题我最早从6月底开始出现。
4.可能与网络或者sign服务器有关，在中国电信网络环境下，我测试发现使用vpn能明显降低这个问题的出现概率。
5.这个问题并非出现后一直持续，有时候会自动恢复，有时候需要重启程序才恢复，还有时候用手机登录相应的QQ随便说句话就会恢复，还有时候开关VPN就可以恢复。

**Comment by sisi0318** [comment]
”我测试发现使用vpn能明显降低这个问题的出现概率“ 引用此条判断为 签名服务器 连通性不好

**Comment by DarkCWK** [comment]
> 我测试发现使用vpn能明显降低这个问题的出现概率

应该就是签名连通性不好，建议测试一下

**Comment by alphaply** [comment]
windows，同样遇到这个问题

**Comment by sweetymajo** [comment]
各位久等了。我经过几天使用不同VPN进行测试，发现确实是签名服务器的连通性问题，至少我的现象与这个问题有关。
我决定关掉这个issue，关联的issue也可以参考我的这个结论进行调查。
