### ISSUE TITLE
[Bug?]: 调用 get_msg 的时候 message_id 为 0

### ISSUE THREAD

**Issue by wling-art** [LagrangeDev/Lagrange.Core#472]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/0fc60937e2d3507cb9f38aee88fdc860505f0f9d

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

在 onebot 协议中使用 get_msg 获取 message_id

### 期望的结果是什么？

获取message对应的id数字

### 实际的结果是什么？

获得0
![image](https://github.com/user-attachments/assets/8ef76afe-0ff1-448a-b9ad-8c3e5d2408f1)

![image](https://github.com/user-attachments/assets/3fa33e87-7d67-4f25-98de-61971e53f677)

**Comment by wling-art** [comment]
Same: 
https://github.com/LagrangeDev/Lagrange.Core/issues/456

**Comment by DarkCWK** [comment]
https://github.com/LagrangeDev/Lagrange.Core/issues/272
