### ISSUE TITLE
反向websocket不验证ssl证书

### ISSUE THREAD

**Issue by 1143910315** [LagrangeDev/Lagrange.Core#475]
### Lagrange项目

Core

### 新需求内容

希望能关闭连接wss协议的时候的证书验证（因为内网穿透的原因，需要使用ssl，但是没有有效证书），通过配置文件关闭ssl证书验证也好

**Comment by CrackTC** [comment]
有没有试过把证书加到系统的证书存储里

**Comment by 1143910315** [comment]
> 有没有试过把证书加到系统的证书存储里

没有弄成功，也不知道是不是自己的问题，如果不方便的话，我想其他办法解决吧
