### ISSUE TITLE
[Bug] get_group_member_info, get_stranger_info 支持不全面

### ISSUE THREAD

**Issue by MuuuShin** [LagrangeDev/Lagrange.Core#48]
如题 似乎只能获取QQ号和at对应的QQ 无法获取昵称

**Comment by happyvalley-lmx** [comment]
有类似的问题，走Onebot的at的时候一开始只显示数字，但似乎重新点进去at就出来了，也不知道是什么原理

**Comment by Mag1Catz** [comment]
走onebot的时候event(GroupMessageEvent).sender.card也无法获取到群名片。
具体位置在 https://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E7%BE%A4%E6%B6%88%E6%81%AF

**Comment by MuuuShin** [comment]
> 走onebot的时候event(GroupMessageEvent).sender.card也无法获取到群名片。 具体位置在 https://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E7%BE%A4%E6%B6%88%E6%81%AF
可以尝试一下pr里的代码,还没有被接受.但是楼主试了一下应该是可以用的

**Comment by Linwenxuan05** [comment]
没写这个（

**Comment by MuuuShin** [comment]
想了想还是reopen一下 毕竟stranger_info基本无法被完全实现了
请看此discussion作为替代解决方案:discussion https://github.com/LagrangeDev/Lagrange.Core/discussions/53

**Comment by lava081** [comment]
get_group_member_info响应的sex字段似乎是 '' 而不是 male 或 female 或 unknown

**Comment by DarkCWK** [comment]
> get_group_member_info响应的sex字段似乎是 '' 而不是 male 或 female 或 unknown

此 api 不在这个 issue 讨论范围
请在 #152 讨论

**Comment by DarkCWK** [comment]
目前的 get_stranger_info 方案是从所有的群中获取信息

**Comment by MuuuShin** [comment]
> 目前的 `get_stranger_info` 方案是从所有的群中获取信息

所以目前stanger也算是做了？那我就可以关我的discussion了吗

**Comment by DarkCWK** [comment]
> 所以目前stanger也算是做了？那我就可以关我的discussion了吗

但是不全面啊（

**Comment by MuuuShin** [comment]
> > 所以目前stanger也算是做了？那我就可以关我的discussion了吗
> 
> 但是不全面啊（ discussion 大概是可以关了?

我感觉看描述跟我的discussion差不多实现，我先关了，issue先留着吧

**Comment by DarkRRb** [comment]
fix on 7b925bb8ad0f955f18797d4807b9f214bedf1f64
