### ISSUE TITLE
发送qq音乐m4a文件报错  mp3不报错

### ISSUE THREAD

**Issue by wzwei1990** [LagrangeDev/Lagrange.Core#480]
### Lagrange项目

OneBot

### 新需求内容

发送qq音乐m4a文件报错  mp3不报错
![e5b71d3a3d38de1764ffe2f463045ba](https://github.com/user-attachments/assets/d630fc74-1266-4286-a301-feef5575c1aa)
![505075b316645cc2fe2006f7d62a0e6](https://github.com/user-attachments/assets/c25053ec-c200-4396-ba73-69ef718d7ad7)

**Comment by Linwenxuan04** [comment]
拉格兰不内置ffmepg 请自行解决转码问题（encode到silk或者encode到mp3再经过拉格兰内置encoder

**Comment by wzwei1990** [comment]
请问发送视频mp4会过期打不开什么原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LagrangeDev/Lagrange.Core] 发送qq音乐m4a文件报错  mp3不报错 (Issue #480)




 
拉格兰不内置ffmepg 请自行解决转码问题（encode到silk或者encode到mp3再经过拉格兰内置encoder
