### ISSUE TITLE
[Bug?]: onebot 自定义合并转发消息显示异常

### ISSUE THREAD

**Issue by NoMathExpectation** [LagrangeDev/Lagrange.Core#481]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

319785cbd92b767e67f0db4e32738e60b9c48145

### 运行环境

Linux

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

使用 onebot 实现端（这里用的是[simbot](https://github.com/simple-robot/simbot-component-onebot)）对 lagrange.onebot 直接发送含 onebot 自定义 node 节点的请求，例如：
`{"message_type":"group","group_id":"*","message":[{"type":"node","data":{"user_id":"*","nickname":"*","content":[{"type":"text","data":{"text":"lo\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nng"}}]}}],"auto_escape":true}`

### 期望的结果是什么？

正确展示合并转发消息

### 实际的结果是什么？

发送出来的内容为 `该消息类型暂不支持查看`

### Trace 级别日志记录（可选）

```Shell
info: Lagrange.OneBot.Core.Network.Service.HttpService[2]
      Request(Conn: 9527214b-aa8f-4fcd-96b7-7e4d51777f1c from 172.29.0.3:41332)
info: Lagrange.OneBot.Core.Network.Service.HttpService[3]
      Receive(Conn: 9527214b-aa8f-4fcd-96b7-7e4d51777f1c: {"message_type":"group","group_id":"*","message":[{"type":"node","data":{"user_id":"*","nickname":"*","content":[{"type":"text","data":{"text":"lo\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nng"}}]}}],"auto_escape":true})
info: Lagrange.OneBot.Core.Network.Service.HttpService[3]
      Receive(Conn: 9527214b-aa8f-4fcd-96b7-7e4d51777f1c: {"action":"send_msg","params":{"message_type":"*","group_id":"*","message":[{"type":"node","data":{"user_id":"*","nickname":"*","content":[{"type":"text","data":{"text":"lo\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nng"}}]}}],"auto_escape":true}})
trce: Lagrange.Core.BotContext[0]
      [2024-08-05 08:35:27] [ServiceContext] [DEBUG]: Outgoing SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.Core.BotContext[0]
      [2024-08-05 08:35:28] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
trce: Lagrange.Core.BotContext[0]
      [2024-08-05 08:35:28] [ServiceContext] [DEBUG]: Incoming SSOFrame: MessageSvc.PbSendMsg
trce: Lagrange.OneBot.Core.Network.Service.HttpService[4]
      Send(Conn: 9527214b-aa8f-4fcd-96b7-7e4d51777f1c: {"status":"ok","retcode":0,"data":{"message_id":*},"echo":null})
```

### 补充说明（可选）

simple-robot/simbot-component-onebot#68

**Comment by CrackTC** [comment]
Lagrange.OneBot 的合并转发消息要通过[扩展api](https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/API/Extend/)发送

**Comment by NoMathExpectation** [comment]
> Lagrange.OneBot 的合并转发消息要通过[扩展api](https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/API/Extend/)发送

诶，我看其他onebot服务端是不需要额外的api的，比如补充里的issue提到的其他服务端

**Comment by ishkong** [comment]
从go-cqhttp时开始，与合并转发相关的操作一直是单独的api。
且由于发送合并转发的逻辑与发送其它消息有一定的区别，lgr暂时没有兼容的计划。
这并不是一个bug，所以关闭此issue。
你可以选择提交一个feature request来请求开发者支持，或者使用其它服务端.
