### ISSUE TITLE
[Bug?]: 发送音频消息后手机能正常播放但是电脑端播放无效

### ISSUE THREAD

**Issue by NoNameGMM** [LagrangeDev/Lagrange.Core#484]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

commit-8aee49a

### 运行环境

Windows

### 运行架构

arm64

### 连接方式

None

### 重现步骤

音频文件是一个长为212秒的mp3

发送后手机端和电脑端都能接收到消息
但只有手机端能正常播放

### 期望的结果是什么？

手机端和电脑端都正常播放

### 实际的结果是什么？

只有手机端能正常播放
手机端：
![1345abd39cc361d5af1237219713668f](https://github.com/user-attachments/assets/acb91ca3-c245-43cb-84ba-1a37437bc068)
电脑端：
![b8e04bd3c1957a339c741fd834e2510f](https://github.com/user-attachments/assets/2c4fc96b-dad7-4bac-82ff-96e06095aa29)

### 简单的复现代码/链接（可选）

```C#
var groupMessageChain = MessageBuilder.Group(groupid).Record(recordpath, 212);
var result = await bot.SendMessage(groupMessageChain.Build());
```

**Comment by Linwenxuan04** [comment]
大概率是转出来的silk的rate太高了 建议使用自己的silk encoder
