### ISSUE TITLE
[Feature Request]: 未来会有支持表情表态吗？

### ISSUE THREAD

**Issue by MerlinCN** [LagrangeDev/Lagrange.Core#485]
### Lagrange项目

Core

### 新需求内容

表态回复以及表态事件

**Comment by Linwenxuan04** [comment]
现在就有啊

**Comment by MerlinCN** [comment]
> 现在就有啊

我看文档的拓展API没有看到

**Comment by CwkDark** [comment]
> > 现在就有啊
> 
> 我看文档的拓展API没有看到

文档处于修缮状态, 目前没有更新

你可以查看相关源代码来获取 API

[SetGroupReactionOperation](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Operation/Group/SetGroupReactionOperation.cs)

[OneBotSetGroupReaction](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Entity/Action/OneBotSetGroupReaction.cs)

**Comment by MerlinCN** [comment]
> > > 现在就有啊
> > 
> > 
> > 我看文档的拓展API没有看到
> 
> 文档处于修缮状态, 目前没有更新
> 
> 你可以查看相关源代码来获取 API
> 
> [SetGroupReactionOperation](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Operation/Group/SetGroupReactionOperation.cs)
> 
> [OneBotSetGroupReaction](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Entity/Action/OneBotSetGroupReaction.cs)

明白，看到了发送GroupReaction，有类似GroupReactionEvent吗？
