### ISSUE TITLE
使用多个反向ws连接时会无法连接到其中一个

### ISSUE THREAD

**Issue by happyvalley-lmx** [LagrangeDev/Lagrange.Core#49]
在Implementations下配置了两条连接，之前一直都是正常的。
更新到 Actions [6988945049](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/6988945049) 后，只有其中一个连接能正常连通，连通的那条会将一条消息识别成两条，发送消息时会发送四条甚至六条；另一个连接无法正确接收及发送信息。
![一张截图](https://github.com/LagrangeDev/Lagrange.Core/assets/16506528/0199f251-c6e4-4ebe-9c9c-374e0a1327d4)

**Comment by Linwenxuan05** [comment]
贴一下你的appsettings.json 记得隐去重要信息

**Comment by Linwenxuan05** [comment]
可能在 https://github.com/LagrangeDev/Lagrange.Core/commit/d7f93a99c8db5ec76a2a4c651194e4347a1f009c 修好了 试一试？

**Comment by happyvalley-lmx** [comment]
测试新commit下正常
