### ISSUE TITLE
[Bug?]: ForwardWebSocket 断开连接时 会卡住bot端20秒

### ISSUE THREAD

**Issue by shoucandanghehe** [LagrangeDev/Lagrange.Core#490]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

Docker IMAGE ID 29337d7b3d51

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

1. 开启正向WS
2. 使用NoneBot连接Lagrange
3. 退出NoneBot
4. NoneBot退出时卡住20s

### 期望的结果是什么？

NoneBot退出时不被卡住

### 实际的结果是什么？

NoneBot退出时卡住20s

### Trace 级别日志记录（可选）

```Shell
lagrange  | info: Lagrange.OneBot.Core.Network.Service.ForwardWSService[10]
lagrange  |       The server is started at http://*:8081/
lagrange  | info: Lagrange.OneBot.Core.Network.Service.ForwardWSService[11]
lagrange  |       Connect(65dbc6a4-cdd5-4899-b294-9380a211ec82)
lagrange  | trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[13]
lagrange  |       Send(65dbc6a4-cdd5-4899-b294-9380a211ec82) {"sub_type":"connect","meta_event_type":"lifecycle","time":1723443827,"self_id":3651396264,"post_type":"meta_event"}
lagrange  | trce: Lagrange.OneBot.Core.Network.Service.ForwardWSService[13]
lagrange  |       Send(65dbc6a4-cdd5-4899-b294-9380a211ec82) {"interval":5000,"status":{"app_initialized":true,"app_enabled":true,"app_good":true,"online":true,"good":true},"meta_event_type":"heartbeat","time":1723443827,"self_id":3651396264,"post_type":"meta_event"}
lagrange  | info: Lagrange.OneBot.Core.Network.Service.ForwardWSService[14]
lagrange  |       Disconnect(65dbc6a4-cdd5-4899-b294-9380a211ec82)
lagrange  | trce: Lagrange.Core.BotContext[0]
lagrange  |       [2024-08-12 06:23:52] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
lagrange  | trce: Lagrange.Core.BotContext[0]
lagrange  |       [2024-08-12 06:24:02] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
lagrange  | trce: Lagrange.Core.BotContext[0]
lagrange  |       [2024-08-12 06:24:12] [ServiceContext] [DEBUG]: Outgoing SSOFrame: Heartbeat.Alive
```

### 补充说明（可选）

NB端除了OB11没有加载任何其他东西
![595f478adabdfff898bfdf920439cc1b](https://github.com/user-attachments/assets/988cc98f-a7e5-42b3-9c05-6178653e6ffc)
NapCatQQ
![0fb09851704351d01c9a447301a91349](https://github.com/user-attachments/assets/24b7e290-b52f-49c6-bf62-3314e9d51d9b)
Lagrange

**Comment by CwkDark** [comment]
请移步到 nonebot 的 issue, 根据 LagrangeDev 的日志, 这个连接已经完全断开了

**Comment by CwkDark** [comment]
或者你可以提供一下你的 NoneBot 项目的代码么？

**Comment by shoucandanghehe** [comment]
> 或者你可以提供一下你的 NoneBot 项目的代码么？

NB端除了OB11没有加载任何其他东西

**Comment by CwkDark** [comment]
> > 或者你可以提供一下你的 NoneBot 项目的代码么？
> 
> NB端除了OB11没有加载任何其他东西

那你提供一下配置可以么？
另外问问 `Disconnect(65dbc6a4-cdd5-4899-b294-9380a211ec82)` 是关闭之后马上打印的还是等待20s之后才打印的？

**Comment by shoucandanghehe** [comment]
https://github.com/user-attachments/assets/c1554652-a02b-4bed-b864-7d912d03020e

**Comment by 2mf8** [comment]
> out.mp4

这是NB的问题吧，对接其他应用端也这样吗？还是只有lgr这样？

**Comment by shoucandanghehe** [comment]
> 这是NB的问题吧，对接其他应用端也这样吗？还是只有lgr这样？

可以看补充说明，napcatqq并没有这个问题

**Comment by 2mf8** [comment]
> > out.mp4
> 
> 这是NB的问题吧，对接其他应用端也这样吗？还是只有lgr这样？

试试[Go-Lagrange-client](https://github.com/2mf8/Go-Lagrange-Client/releases)

**Comment by shoucandanghehe** [comment]
> 试试[Go-Lagrange-client](https://github.com/2mf8/Go-Lagrange-Client/releases)

Go-Lagrange-client怎么配正向ws（

**Comment by 2mf8** [comment]
> > 试试[Go-Lagrange-client](https://github.com/2mf8/Go-Lagrange-Client/releases)
> 
> Go-Lagrange-client怎么配正向ws（

启动后自动启动正向，有地址

**Comment by 2mf8** [comment]
> > > 试试[Go-Lagrange-client](https://github.com/2mf8/Go-Lagrange-Client/releases)
> > 
> > 
> > Go-Lagrange-client怎么配正向ws（
> 
> 启动后自动启动正向，有地址

地址在日志里

**Comment by shoucandanghehe** [comment]
> 试试[Go-Lagrange-client](https://github.com/2mf8/Go-Lagrange-Client/releases)

@2mf8 https://github.com/2mf8/Go-Lagrange-Client/issues/21

**Comment by CwkDark** [comment]
Linux 下无法复现
![image](https://github.com/user-attachments/assets/8015ed1a-e11b-4010-b280-ee6093c3bb86)

Windows 待测

**Comment by yanyongyu** [comment]
看nb日志输出的时间是正常的，可能是有东西卡住了日志打印到控制台，不是nb本身卡住

**Comment by shoucandanghehe** [comment]
试了一下aiohttp作为nb的WebSocket驱动，正常
所以是websockets的问题？

**Comment by CwkDark** [comment]
windows 下也没有复现成功
![image](https://github.com/user-attachments/assets/2b079ce2-78d2-4c01-ba73-e46df7167450)

**Comment by shoucandanghehe** [comment]
@CwkDark 根据websockets日志看大概是tcp连接没有正确关闭
![image](https://github.com/user-attachments/assets/9a21bcec-255e-4ba7-b1f8-29da7efe13cc)

**Comment by CwkDark** [comment]
成功复现, 目前是仅在 Linux 上出现, 问题排查中
