### ISSUE TITLE
[Bug?]: 发送Markdown消息失败

### ISSUE THREAD

**Issue by NoNameGMM** [LagrangeDev/Lagrange.Core#493]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

最新

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

在发送消息后后，返回result.Result为0
但是并没有成功将消息发出

### 期望的结果是什么？

正确的发送消息

### 实际的结果是什么？

没有成功将消息发出

### 简单的复现代码/链接（可选）

```C#
实现方法：
public async static Task SendGroupMarkDown(uint groupid, string markdown)
{
    var bot = GlobalBotContext.BotContextInstance;
    var groupMessageChain = MessageBuilder.Group(groupid)
        .Markdown(markdown);
    var result = await bot.SendMessage(groupMessageChain.Build());
    if (result.Result == 120)
    {
        BotLog.logwarn("消息状态: " + result.Result + " 您的机器人被禁言 消息无法发出");
    }
    else if (result.Result == 16)
    {
        BotLog.logwarn("消息状态: " + result.Result + " 您需要发送的群号未找到");
    }
    else
    {
        BotLog.logtip("消息状态: " + result.Result + " 您的消息发送成功！");
    }
}

使用：
await SendGroupMarkDown(群号, "{\"content\": \"# 哈喽\"}");
```

**Comment by 2mf8** [comment]
不支持直发，双转发可以

**Comment by Linwenxuan04** [comment]
Markdown消息早在4月份就已经无法被发出

**Comment by NoNameGMM** [comment]
请问一下
为什么官方的Bot文档中
还能支持MarkDown发送

**Comment by 2mf8** [comment]
> 请问一下 为什么官方的Bot文档中 还能支持MarkDown发送

官机关我拉格兰什么事？官机有DAU限制，还要申请审核

**Comment by 2mf8** [comment]
> 请问一下 为什么官方的Bot文档中 还能支持MarkDown发送

拉格兰也能发，只是要双转发罢了（双合并转发）

**Comment by NoNameGMM** [comment]
> > 请问一下 为什么官方的Bot文档中 还能支持MarkDown发送
> 
> 拉格兰也能发，只是要双转发罢了（双合并转发）

好的我明白了（谢谢
