### ISSUE TITLE
[Feature Request]: 自动处理 onebot 发送的 node 格式自定义合并转发

### ISSUE THREAD

**Issue by NoMathExpectation** [LagrangeDev/Lagrange.Core#494]
### Lagrange项目

OneBot

### 新需求内容

如 #481 所说，目前 onebot 的 node 格式自定义合并转发是需要先调用拓展api来创建合并转发再发送的，直接通过标准的 api 发送会显示异常。如果能够在发送 node 格式的自定义合并转发时，自动处理并创建对应的合并转发来发送，这样子能够更加方便自定义合并转发。

**Comment by DarkRRRabbit** [comment]
目前已有 `send_private_forward_msg` 和 `send_group_forward_msg`

**Comment by NoMathExpectation** [comment]
> 目前已有 `send_private_forward_msg` 和 `send_group_forward_msg`

...有没有可能，就是因为不能直接在消息里包含自定义合并转发节点，而是要调用拓展api来发送，所以才提出这个feature request的

**Comment by DarkRRRabbit** [comment]
> ...有没有可能，就是因为不能直接在消息里包含自定义合并转发节点，而是要调用拓展api来发送，所以才提出这个feature request的

好哦
