### ISSUE TITLE
[Feature Request]: Qzone fast-login port

### ISSUE THREAD

**Issue by gfhdhytghd** [LagrangeDev/Lagrange.Core#499]
### Lagrange项目

Core

### 新需求内容

开发者你好，我非常喜欢Lagrange项目，尤其是其相比其他基于NTQQ项目的低性能开销，但是因为我的项目涉及到了qq空间，而lagrange开启后并不能实现网页qq快捷登陆，故提出此新功能建议。

根据csdn的一篇文章，网页快捷登陆是这么实现的：
```
本地QQ客户端监听了4300-4308端口，浏览器通过HTTP请求的方式，向本地QQ客户端发送请求，拿到了当前本地QQ客户端登录的账户信息
https://blog.csdn.net/QIU176161650/article/details/118939808
```

如果开发者有余力且评估风险没有问题的话，我希望lagrange可以在这几个端口提供服务以实现qq的网页快捷登陆

**Comment by Linwenxuan04** [comment]
快速登录容易被灰色产业所利用

**Comment by gfhdhytghd** [comment]
这倒不是啥大问题,灰产想搞的话可以直接挂个ntqq或者用napcat/LLOB
