### ISSUE TITLE
[Bug?]: LightApp消息 发送显示"发送者版本过低，无法展示内容"

### ISSUE THREAD

**Issue by NoNameGMM** [LagrangeDev/Lagrange.Core#501]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

最新

### 运行环境

Windows

### 运行架构

x86

### 连接方式

None

### 重现步骤

正常发送LightApp 发送成功
但发送出来的并不是LightApp 而是 “发送者版本过低，无法展示内容”

### 期望的结果是什么？

能够正常发送消息

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/913e682e-a4f1-445f-a430-642b58998209)

### 简单的复现代码/链接（可选）

```C#
public async static Task SendGroupLightApp(uint groupid)
{
    var bot = GlobalBotContext.BotContextInstance;
    var myObject = new
    {
        app = "com.tencent.miniapp",
        desc = "",
        view = "notification",
        ver = "0.0.0.1",
        prompt = "Test的今日人品",
        meta = new
        {
            notification = new
            {
                appInfo = new
                {
                    appName = "Test的今日人品",
                    appType = 4,
                    appid = 1234567890,
                    iconUrl = "http://q1.qlogo.cn/g?b=qq&nk=1234567890&s=640"
                },
                data = new[]
                {
                    new { title = "今日人品", value = "Test" },
                    new { title = "今日适宜", value = "Test" },
                    new { title = "一言", value = "Test --Test" }
                },
                title = "",
                emphasis_keyword = "今日人品"
            }
        }
    };
    var groupMessageChain = MessageBuilder.Group(groupid)
        .LightApp(JsonSerializer.Serialize(myObject));
    var result = await bot.SendMessage(groupMessageChain.Build());
}
```

**Comment by Linwenxuan04** [comment]
因为LightApp要求Token才能发出 请自行寻找LightApp所使用的token签名接口
