### ISSUE TITLE
[Feature Request]: 可以添加发送群临时消息功能吗

### ISSUE THREAD

**Issue by jeanhua** [LagrangeDev/Lagrange.Core#507]
### Lagrange项目

Core

### 新需求内容

目前我看只能构造群聊和朋友消息，但是没有群临时会话，但是有群临时会话的委托事件，所以希望添加一个群临时会话的消息链构造

**Comment by jeanhua** [comment]
还有那个fakegroup是干嘛的啊，发送之后就直接发群里面了

**Comment by Linwenxuan04** [comment]
不可以 有被黑产利用风险
