### ISSUE TITLE
[Feature Request]: 希望 Lagrange.Onebot 新增 .handle_quick_operation

### ISSUE THREAD

**Issue by kamenomi-dev** [LagrangeDev/Lagrange.Core#510]
### Lagrange项目

OneBot

### 新需求内容

在 Onebot v11 标准中，有一个API —— .handle_quick_operation 被制定，目的为了使事件消息得到快捷操作。
在 #337 中首次提出并由 ghost 用户答复未实现此api并设其为 Not planned，且如今现行Nightly中并未实现此 api 。
我希望 Lagrane.Core 开发者可以提供完善该API，为生态提供便利的接口，谢谢！

**Comment by sisi0318** [comment]
目前没有计划考虑实现
