### ISSUE TITLE
当接受到错误的信息时会导致整个程序退出

### ISSUE THREAD

**Issue by DarkCWK** [LagrangeDev/Lagrange.Core#52]
任意一个ws产生异常会导致整个程序退出
![图片](https://github.com/LagrangeDev/Lagrange.Core/assets/20531116/8c8c2805-e8a1-4641-abd2-8bd3d46c9b28)
例如接受到一个错误的json字符串

**Comment by Linwenxuan05** [comment]
懒得加全局Global Exception
至于这个有空的时候加一个tryexcept好了
