### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by zyhqwq** [LagrangeDev/Lagrange.Core#535]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

ASP.NET Core 运行时 8.0.8.NET SDKs 8.0.401

### 运行环境

Linux

### 运行架构

arm64

### 连接方式

None

### 重现步骤

手动下载ASP.NET Core 运行时 8.0.8.NET SDKs 8.0.401后./Lagrange.OneBot运行

### 期望的结果是什么？

可以正常运行Lagrange.OneBot

### 实际的结果是什么？

手动下载ASP.NET Core 运行时 8.0.8.NET SDKs 8.0.401，但还是提示
You must install .NET to run this application.

App: /root/qqnt/Lagrange.OneBot
Architecture: arm64
App host version: 8.0.8
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=linux-arm64&os=debian.11&apphost_version=8.0.8
并且dotnet --info输出
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

运行时环境:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /root/sdk8.0.4/sdk/8.0.401/

已安装 .NET 工作负载:
配置为在安装新清单时使用 loose manifests。
没有要显示的已安装工作负载。

Host:
  Version:      8.0.8
  Architecture: arm64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/root/sdk8.0.4/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/root/sdk8.0.4/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/root/sdk8.0.4/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
root@8Gufi003:~/qqnt# ls
Lagrange.OneBot
root@8Gufi003:~/qqnt# ./Lagrange.OneBot
You must install .NET to run this application.

App: /root/qqnt/Lagrange.OneBot
Architecture: arm64
App host version: 8.0.8
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=linux-arm64&os=debian.11&apphost_version=8.0.8

**Comment by sisi0318** [comment]
请确保 环境变量 DOTNET_ROOT 有效

**Comment by zyhqwq** [comment]
解决了
root@8Gufi003:~/qqnt# nano ~/.bashrc
添加文件夹路径
export DOTNET_ROOT=/path/to/dotnet
Ctrl+s保存
Ctrl+x退出
root@8Gufi003:~/qqnt# source ~/.bashrc
root@8Gufi003:~/qqnt# ./Lagrange.OneBot
就可以了
