### ISSUE TITLE
[Bug?]: 禁止登录

### ISSUE THREAD

**Issue by liangchaowei1** [LagrangeDev/Lagrange.Core#543]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/releases/download/nightly/Lagrange.OneBot_linux-x64_net8.0_SelfContained.tar.gz

### 运行环境

Linux

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

扫码登录报更新qq版本

### 期望的结果是什么？

登录成功

### 实际的结果是什么？

Tag: 禁止登录

### Trace 级别日志记录（可选）

```Shell
./Lagrange.OneBot
warn: Lagrange.OneBot.Utility.MusicSigner[0]
      MusicSignServer is not available, sign may be failed
info: Lagrange.OneBot.LagrangeAppBuilder[0]
      Indexing in the database...
info: Lagrange.OneBot.LagrangeAppBuilder[0]
      The first indexing of the old database will load the entire database into memory.
info: Lagrange.OneBot.LagrangeAppBuilder[0]
      If this is the first time creating an index for the old database, please restart the application
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /opt/Lagrange.OneBot/bin/Release/net8.0/linux-x64/publish
info: Lagrange.OneBot.LagrangeApp[0]
      Lagrange.OneBot Implementation has started
info: Lagrange.OneBot.LagrangeApp[0]
      Protocol:  | 3.2.10-25765
info: Lagrange.OneBot.LagrangeApp[0]
      Session expired or Password not filled in, try to login by QrCode
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:19] [WtExchangeLogic] [INFORMATION]: Connecting Servers...
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:20] [SocketContext] [VERBOSE]: Server: http://120.232.130.13:8080/ Latency: 11
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:20] [SocketContext] [VERBOSE]: Server: http://120.233.18.186:8080/ Latency: 12
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:20] [SocketContext] [VERBOSE]: Server: http://120.233.17.147:8080/ Latency: 13
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:20] [SocketContext] [VERBOSE]: Server: http://120.241.130.195:8080/ Latency: 13
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:20] [SocketContext] [VERBOSE]: Server: http://120.241.130.216:8080/ Latency: 14
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:21] [WtExchangeLogic] [INFORMATION]: QrCode Fetched, Expiration: 120 seconds
info: Lagrange.OneBot.LagrangeApp[0]
      Please scan the QR code above, Url: https://txz.qq.com/p?k=DOlpGP9z767PcsCIZR7y3m4x4wgjxtgD&f=1600001615
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:24] [WtExchangeLogic] [INFORMATION]: QrCode State Queried: WaitingForScan Uin: 0
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:26] [WtExchangeLogic] [INFORMATION]: QrCode State Queried: WaitingForScan Uin: 0
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:28] [WtExchangeLogic] [INFORMATION]: QrCode State Queried: Confirmed Uin: 723234428
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:28] [WtExchangeLogic] [INFORMATION]: QrCode Confirmed, Logging in with A1 sig...
info: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:28] [WtExchangeLogic] [INFORMATION]: Doing Login...
fail: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:28] [WtExchangeLogic] [FATAL]: Login failed: 45
fail: Lagrange.Core.BotContext[0]
      [2024-08-22 23:31:28] [WtExchangeLogic] [FATAL]: Tag: 禁止登录
      State: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
```

**Comment by liangchaowei1** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "SignServerUrl": "https://sign.lagrangecore.org/api/sign",
  "Account": {
    "Uin": 0,
    "Password": "",
    "Protocol": "Linux",
    "AutoReconnect": true,
    "GetOptimumServer": true
  },
  "Message": {
    "IgnoreSelf": true,
    "StringPost": false
  },
  "QrCode": {
    "ConsoleCompatibilityMode": false
  },
  "Implementations": [
   
    {
      "Type": "ForwardWebSocket",
      "Host": "*",
      "Port": 8081,
      "HeartBeatInterval": 5000,
      "HeartBeatEnable": true,
      "AccessToken": ""
    },
    {
      "Type": "Http",
      "Host": "*",
      "Port": 3000,
      "AccessToken": ""
    }
  ]
}配置文件

**Comment by liangchaowei1** [comment]
ping -c 20 sign.lagrangecore.org
PING sign.lagrangecore.org (104.21.51.166) 56(84) bytes of data.
64 bytes from 104.21.51.166 (104.21.51.166): icmp_seq=1 ttl=51 time=202 ms
64 bytes from 104.21.51.166 (104.21.51.166): icmp_seq=2 ttl=51 time=202 ms
64 bytes from 104.21.51.166 (104.21.51.166): icmp_seq=3 ttl=51 time=202 ms
64 bytes from 104.21.51.166 (104.21.51.166): icmp_seq=4 ttl=51 time=202 ms
64 bytes from 104.21.51.166 (104.21.51.166): icmp_seq=6 ttl=51 time=202 ms
^C
--- sign.lagrangecore.org ping statistics ---
7 packets transmitted, 5 received, 28.5714% packet loss, time 6014ms
rtt min/avg/max/mdev = 202.002/202.032/202.072/0.025 ms
签名地址

**Comment by RTAkland** [comment]
是不是签名地址没更新, 最新的签名地址是 `https://sign.lagrangecore.org/api/sign/25765`

**Comment by liangchaowei1** [comment]
> 是不是签名地址没更新, 最新的签名地址是 `https://sign.lagrangecore.org/api/sign/25765`

谢谢 是签名问题，已处理，tg群链接有吗

**Comment by RTAkland** [comment]
> > 是不是签名地址没更新, 最新的签名地址是 `https://sign.lagrangecore.org/api/sign/25765`
> 
> 谢谢 是签名问题，已处理，tg群链接有吗

https://t.me/+6HNTeJO0JqtlNmRl
