### ISSUE TITLE
Actions [OneBot] Fixed NotifyService.cs#117 版本在正向 WebSocket 的 /event 路径无法收到消息

### ISSUE THREAD

**Issue by DarkCWK** [LagrangeDev/Lagrange.Core#56]
[[OneBot] Fixed NotifyService.cs#117](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/7231725320) 中的 `Lagrange.OneBot_linux-x64` 版本无法在正向 WebSocket 的 /event 路径收到消息

查看日志有警告信息
```
warn: Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection[6]
      [LagrangeWebSvcCollection]: WebService send message failed.
      Fleck.ConnectionNotAvailableException: Data sent while closing or after close. Ignoring.
         at Lagrange.OneBot.Core.Network.Service.ForwardWSService.SendJsonAsync[T](T json, String identifier, CancellationToken cancellationToken)
         at Lagrange.OneBot.Core.Network.LagrangeWebSvcCollection.SendJsonAsync[T](T json, String identifier, CancellationToken cancellationToken)
```

上个版本 [
[Core] Fixed that newFace would not be parsed correctly #116 ](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/7231627556) 的 `
Lagrange.OneBot_linux-x64` 可以收到消息

**Comment by Linwenxuan05** [comment]
理论上这两个版本不应该出现此问题 因为就改了NotifyService的注入和调用形式

**Comment by DarkCWK** [comment]
在 Actions#116 版本是可以受到消息的，但是似乎长时间运行后就收不到了，更之前的版本还没有测试

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DarkCWK** [comment]
测试后发现，似乎是断开一次后，就无法收到消息了

**Comment by DarkCWK** [comment]
> 理论上这两个版本不应该出现此问题 因为就改了NotifyService的注入和调用形式

在 
[[Core] Fixed that newFace would not be parsed correctly #116](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/7231627556) 版本是可以受到消息的，但是似乎长时间运行后就收不到了，更之前的版本还没有测试

**Comment by DarkCWK** [comment]
这个是客户端的问题, 不是拉格兰的问题
