### ISSUE TITLE
[Feature Request]: 希望增加消息Reaction的API

### ISSUE THREAD

**Issue by BEISNWKZNAN** [LagrangeDev/Lagrange.Core#562]
### Lagrange项目

Core

### 新需求内容

_![image](https://github.com/user-attachments/assets/b133ecc7-05f3-41ee-89ce-8cbe0fd36a91)
希望对于这种Reaction可以提供根据消息获取Reaction列表以及对应数量的API，Reaction变化时的事件。

**Comment by RTAkland** [comment]
我听群内的开发人员说已经有了但是似乎不能用onebot发送只能通过.core的api调用发送

**Comment by ishkong** [comment]
reaction变化时事件已经有了

获取好像是没有办法，tx目前通过olpush下发，没有能够查询的包，只能自己做本地缓存

**Comment by BEISNWKZNAN** [comment]
> reaction变化时事件已经有了
> 
> 获取好像是没有办法，tx目前通过olpush下发，没有能够查询的包，只能自己做本地缓存

确实已经有了，谢谢
