### ISSUE TITLE
Sign server如何私有部署？

### ISSUE THREAD

**Issue by yukozh** [LagrangeDev/Lagrange.Core#570]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

3

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

官方提供的Sign server经常无法使用，想自行部署sign服务器

![image](https://github.com/user-attachments/assets/4146bed5-754a-41c2-9777-ade73f385144)

### 期望的结果是什么？

1

### 实际的结果是什么？

2

**Comment by HornCopper** [comment]
或许这个不算是bug（

**Comment by Coloryr** [comment]
```
warn: Lagrange.Core.BotContext[0]
      [2024-09-03 18:18:24] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
warn: Lagrange.Core.BotContext[0]
      [2024-09-03 18:18:24] [BusinessContext] [WARNING]: System.Exception: Signer version mismatch
         at Lagrange.OneBot.Utility.OneBotSigner.Sign(String cmd, UInt32 seq, Byte[] body, Byte[]& e, String& t) in E:\temp_code\Lagrange.Core\Lagrange.OneBot\Utility\OneBotSigner.cs:line 92
         at Lagrange.Core.Internal.Packets.SsoPacker.Build(SsoPacket packet, BotAppInfo appInfo, BotDeviceInfo device, BotKeystore keystore, SignProvider signProvider) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Packets\SsoPacker.cs:line 21
         at Lagrange.Core.Internal.Context.PacketContext.SendPacket(SsoPacket packet) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\PacketContext.cs:line 47
         at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\BusinessContext.cs:line 104
```
但是寄了

**Comment by Lilyltt** [comment]
不支持自己部署,考虑使用SignProxyUrl挂代理

**Comment by PYUDNG** [comment]
> ```
> warn: Lagrange.Core.BotContext[0]
>       [2024-09-03 18:18:24] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
> warn: Lagrange.Core.BotContext[0]
>       [2024-09-03 18:18:24] [BusinessContext] [WARNING]: System.Exception: Signer version mismatch
>          at Lagrange.OneBot.Utility.OneBotSigner.Sign(String cmd, UInt32 seq, Byte[] body, Byte[]& e, String& t) in E:\temp_code\Lagrange.Core\Lagrange.OneBot\Utility\OneBotSigner.cs:line 92
>          at Lagrange.Core.Internal.Packets.SsoPacker.Build(SsoPacket packet, BotAppInfo appInfo, BotDeviceInfo device, BotKeystore keystore, SignProvider signProvider) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Packets\SsoPacker.cs:line 21
>          at Lagrange.Core.Internal.Context.PacketContext.SendPacket(SsoPacket packet) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\PacketContext.cs:line 47
>          at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\BusinessContext.cs:line 104
> ```
> 
> 但是寄了

我这里也遇到了同样的问题（windows和linux_x64都遇到了，nightly和actions最新构建均有测试过），显示signer version mismatch，已经挂了代理，浏览器可以访问https://sign.lagrangecore.org/api/sign（浏览器访问显示`The server is based on the manual calculation of college students!`），已经各处搜寻了文档和issues最后只能找到这里，可以麻烦帮忙看一下吗？

**Comment by Diam2023** [comment]
> > ```
> > warn: Lagrange.Core.BotContext[0]
> >       [2024-09-03 18:18:24] [BusinessContext] [WARNING]: Error when processing the event: Lagrange.Core.Internal.Event.Login.TransEmpEvent
> > warn: Lagrange.Core.BotContext[0]
> >       [2024-09-03 18:18:24] [BusinessContext] [WARNING]: System.Exception: Signer version mismatch
> >          at Lagrange.OneBot.Utility.OneBotSigner.Sign(String cmd, UInt32 seq, Byte[] body, Byte[]& e, String& t) in E:\temp_code\Lagrange.Core\Lagrange.OneBot\Utility\OneBotSigner.cs:line 92
> >          at Lagrange.Core.Internal.Packets.SsoPacker.Build(SsoPacket packet, BotAppInfo appInfo, BotDeviceInfo device, BotKeystore keystore, SignProvider signProvider) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Packets\SsoPacker.cs:line 21
> >          at Lagrange.Core.Internal.Context.PacketContext.SendPacket(SsoPacket packet) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\PacketContext.cs:line 47
> >          at Lagrange.Core.Internal.Context.BusinessContext.SendEvent(ProtocolEvent event) in E:\temp_code\Lagrange.Core\Lagrange.Core\Internal\Context\BusinessContext.cs:line 104
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是寄了
> 
> 我这里也遇到了同样的问题（windows和linux_x64都遇到了，nightly和actions最新构建均有测试过），显示signer version mismatch，已经挂了代理，浏览器可以访问https://sign.lagrangecore.org/api/sign（浏览器访问显示`The server is based on the manual calculation of college students!`，linux服务器上curl测试也可以得到同样的response），已经各处搜寻了文档和issues最后只能找到这里，可以麻烦帮忙看一下吗？

打印签名服务器以及自身版本看下是否匹配

https://github.com/LagrangeDev/Lagrange.Core/blob/5e7072c641d738749c016bd5d54a8af2761ce166/Lagrange.OneBot/Utility/OneBotSigner.cs#L92

```csharp
if (versionJson.GetString() != version) throw new Exception("Signer version mismatch" + " server:" + versionJson.GetString() + " current:" + version);
```

**Comment by PYUDNG** [comment]
![image](https://github.com/user-attachments/assets/e5c27877-64bc-4d95-8f19-311514a8a2c4)
签名服务器版本和自身版本

**Comment by PYUDNG** [comment]
我这里解决了，是signurl填写的不对。
具体参考https://github.com/LagrangeDev/Lagrange.Core/issues/543#issuecomment-2306716607
