### ISSUE TITLE
[Bug?]: 在使用最新版本的Lagrange后，仍无法发送视频

### ISSUE THREAD

**Issue by akchiji888** [LagrangeDev/Lagrange.Core#600]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Core

### 所使用/依赖的Lagrange项目对应的commit

907772e

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

var privateMessageChain = MessageBuilder.Friend(_uin).Video(path).Build();
var result = await context.SendMessage(privateMessageChain);
其中，context为bot实例，_uin为用户UIN，path为视频文件完整路径（视频大小约40M）

### 期望的结果是什么？

正常发送视频

### 实际的结果是什么？

QQ接收端显示：该消息类型暂不支持查看

**Comment by akchiji888** [comment]
![image](https://github.com/user-attachments/assets/9936fedb-6e48-4b8d-9d29-d3ab1d8e6f21)

**Comment by pk5ls20** [comment]
请上传**完整Trace日志**

**Comment by akchiji888** [comment]
> 请上传**完整Trace日志**

抱歉，弱弱地问一句：Trace日志在哪……
找了半天真没找到，也没有啥配置文件之类的，只有VS的一堆输出（

**Comment by pk5ls20** [comment]
> > 请上传**完整Trace日志**
> 
> 抱歉，弱弱地问一句：Trace日志在哪…… 找了半天真没找到，也没有啥配置文件之类的，只有VS的一堆输出（

https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/Config/

**Comment by akchiji888** [comment]
啊？问题是我用的也不是OneBot而是Core，没有这玩意儿啊？

**Comment by akchiji888** [comment]
我自己把仓库克隆以后直接生成了Core的nuget包就拿去用了（

**Comment by sisi0318** [comment]
你用core一样可以把关键构造之类的发一下 然后具体说明一下是哪种发不出去

**Comment by sisi0318** [comment]
鉴于你上面说的发出去提示该消息类型暂不支持查看 判断为你构造了个空包来发送

**Comment by Linwenxuan04** [comment]
请订阅OnBotLogEvent以获取完整的Log

**Comment by DarkRRb** [comment]
> 啊？问题是我用的也不是OneBot而是Core，没有这玩意儿啊？

Core 是直接订阅 OnBotLogEvent 事件来获取日志，如果你没做过滤就是 trace 的

**Comment by akchiji888** [comment]
好的好的，等会儿调一下

**Comment by akchiji888** [comment]
`[ServiceContext][2024/10/2 22:48:22]Unsupported SSOFrame Received: StatSvc.SvcReqMSFLoginNotify

[ServiceContext][2024/10/2 22:48:22]Unsuccessful SSOFrame Payload: 10022C3C42B3004D3456075374617453766366145376635265714D53464C6F67696E4E6F746966797D0001009108000106145376635265714D53464C6F67696E4E6F74696679180001061E5151536572766963652E5376635265714D53464C6F67696E4E6F746966791D0000510A022005B50710022001306D46134C6F676F6666204E6F74696669636174696F6E5625596F7572206163636F7574206973206C6F67676564206F666620696E2061205461626C65746C720001010D890C0B8C980CA80C

[ServiceContext][2024/10/2 22:48:22]Unsupported SSOFrame Received: StatSvc.SvcReqMSFLoginNotify

[ServiceContext][2024/10/2 22:48:22]Unsuccessful SSOFrame Payload: 10022C3C42B3004D3656075374617453766366145376635265714D53464C6F67696E4E6F746966797D0001009108000106145376635265714D53464C6F67696E4E6F74696679180001061E5151536572766963652E5376635265714D53464C6F67696E4E6F746966791D0000510A022005B50710022001306D46134C6F676F6666204E6F74696669636174696F6E5625596F7572206163636F7574206973206C6F67676564206F666620696E2061205461626C65746C720001010D890C0B8C980CA80C

[ServiceContext][2024/10/2 22:48:22]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:22]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:22]Unsupported SSOFrame Received: StatSvc.SvcReqMSFLoginNotify

[ServiceContext][2024/10/2 22:48:22]Unsuccessful SSOFrame Payload: 10022C3C42AAD3925556075374617453766366145376635265714D53464C6F67696E4E6F746966797D0001009108000106145376635265714D53464C6F67696E4E6F74696679180001061E5151536572766963652E5376635265714D53464C6F67696E4E6F746966791D0000510A022005B50710022001306D46134C6F676F6666204E6F74696669636174696F6E5625596F7572206163636F7574206973206C6F67676564206F666620696E2061205461626C65746C720001010D890C0B8C980CA80C

[ServiceContext][2024/10/2 22:48:22]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:27]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:27]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:27]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:27]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:27]Outgoing SSOFrame: OidbSvcTrpcTcp.0xfd4_1

[ServiceContext][2024/10/2 22:48:27]Incoming SSOFrame: OidbSvcTrpcTcp.0xfd4_1

[MessagingLogic][2024/10/2 22:48:27][MessageChain(1776941713)] [Text]: 首页

[ServiceContext][2024/10/2 22:48:30]Outgoing SSOFrame: Heartbeat.Alive

[ServiceContext][2024/10/2 22:48:33]Outgoing SSOFrame: MessageSvc.PbSendMsg

[ServiceContext][2024/10/2 22:48:33]Incoming SSOFrame: MessageSvc.PbSendMsg

[ServiceContext][2024/10/2 22:48:37]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:37]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:37]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[ServiceContext][2024/10/2 22:48:38]Incoming SSOFrame: trpc.msg.olpush.OlPushService.MsgPush

[MessagingLogic][2024/10/2 22:48:38][MessageChain(1776941713)] [Text]: 20

[ServiceContext][2024/10/2 22:48:40]Outgoing SSOFrame: Heartbeat.Alive

[ServiceContext][2024/10/2 22:48:50]Outgoing SSOFrame: Heartbeat.Alive

[ServiceContext][2024/10/2 22:48:56]Unsupported SSOFrame Received: MsgPush.PushGroupProMsg

[ServiceContext][2024/10/2 22:48:56]Unsuccessful SSOFrame Payload: 180028013236F0250A322A3008B09DCBBFBBF8CEED0810E19681BD021894BD012094BD012899BAF5B70638F40FA2060C08FBAFFFBC091087E4FE99023A0040016200
[ServiceContext][2024/10/2 22:48:58]Outgoing SSOFrame: OidbSvcTrpcTcp.0x11e9_100

[ServiceContext][2024/10/2 22:48:58]Incoming SSOFrame: OidbSvcTrpcTcp.0x11e9_100

[ServiceContext][2024/10/2 22:48:59]Outgoing SSOFrame: HttpConn.0x6ff_501

[ServiceContext][2024/10/2 22:48:59]Incoming SSOFrame: HttpConn.0x6ff_501

[ServiceContext][2024/10/2 22:48:59]Outgoing SSOFrame: HttpConn.0x6ff_501

[ServiceContext][2024/10/2 22:48:59]Incoming SSOFrame: HttpConn.0x6ff_501

[ServiceContext][2024/10/2 22:49:00]Outgoing SSOFrame: Heartbeat.Alive

[HighwayContext][2024/10/2 22:49:00]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:00]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:01]Highway Block Result: 0 | 0 |  | 

[ServiceContext][2024/10/2 22:49:01]Unsuccessful SSOFrame Payload: 18002801328201F7290A322A3008B09DCBBFBBF8CEED0810E19681BD021895BD012095BD01289CBAF5B70638F40FA2060C089F92F9FF0410A9E8B8DC010A332A313400D387A7809B0218C0D34D20AED34D3400309DA7113500BBF6FA9087071089D395CB073500D3C0A1A9AA0218F3B71020ECB710350030938C033500B08BFD8BEC0A10ECD4B0DB063A0040016200

[ServiceContext][2024/10/2 22:49:01]Unsupported SSOFrame Received: MsgPush.PushGroupProMsg
[HighwayContext][2024/10/2 22:49:01]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:02]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:02]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:02]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:02]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:03]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:04]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:04]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:04]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:05]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:05]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:05]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:05]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:06]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:06]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:06]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:07]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:08]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:08]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:08]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:08]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:09]Highway Block Result: 0 | 0 |  | 

[ServiceContext][2024/10/2 22:49:10]Outgoing SSOFrame: Heartbeat.Alive

[ServiceContext][2024/10/2 22:49:11]Unsupported SSOFrame Received: MsgPush.PushGroupProMsg

[ServiceContext][2024/10/2 22:49:11]Unsuccessful SSOFrame Payload: 180028013236F0250A322A3008DABEB0DAED8086820910F881F01C18D0E748209DE74828A7BAF5B70638DDB50BA2060C0881FCDE9D0E10F9CFFFD7053A0040016200

[HighwayContext][2024/10/2 22:49:14]Highway Block Result: 0 | 0 |  | 

[HighwayContext][2024/10/2 22:49:14]Upload resources for VideoEntity failed

[ServiceContext][2024/10/2 22:49:14]Outgoing SSOFrame: MessageSvc.PbSendMsg

[ServiceContext][2024/10/2 22:49:15]Incoming SSOFrame: MessageSvc.PbSendMsg

[ServiceContext][2024/10/2 22:49:20]Outgoing SSOFrame: Heartbeat.Alive

[ServiceContext][2024/10/2 22:49:21]Unsupported SSOFrame Received: MsgPush.PushGroupProMsg

[ServiceContext][2024/10/2 22:49:21]Unsuccessful SSOFrame Payload: 18002801328201F7290A322A3008B09DCBBFBBF8CEED0810E19681BD021896BD012096BD0128B5BAF5B70638F40FA2060C08838CAC870510FF98EAFD030A332A313400D387A7809B0218C1D34D20AFD34D3400309DA7113500BBF085D8EA09108CEF9AFD043500D3C0A1A9AA0218F4B71020EDB710350030938C033500B094BAF6B80F10BD979FE8063A0040016200`

**Comment by akchiji888** [comment]
@sisi0318 @pk5ls20 这是完整的日志，发送的内容是一个本地已有且能正常打开，播放，编码格式为H.264的MP4文件

**Comment by akchiji888** [comment]
![image](https://github.com/user-attachments/assets/f785b4f9-d817-4165-82e2-53e86edf144d)
这是构建的消息链

**Comment by DarkRRb** [comment]
可否提供一下视频文件？

**Comment by akchiji888** [comment]
https://github.com/user-attachments/assets/3149c676-8f43-4c76-816f-8f4133d2e44a

@DarkRRb 这是发送的视频文件（用BBDown工具从B站上下载的）

**Comment by DarkRRb** [comment]
经过测试, 该视频可以在最新版可以直接发送, 你更新到最新后尝试一下？
