### ISSUE TITLE
[Feature Request]: 希望能实现多后端节点的负载均衡

### ISSUE THREAD

**Issue by Hyperionml** [LagrangeDev/Lagrange.Core#601]
### Lagrange项目

OneBot

### 新需求内容

比如说原来的onebot端和服务端是一对一，但是为了服务端的高可用我会希望把它做成集群，所以我希望lgr能直接帮我完成服务端集群多节点的负载均衡

**Comment by sisi0318** [comment]
鉴于onebotv11 有正反向  再加上多端负载不应该是一个协议端要做的事 此issue关闭

**Comment by 2mf8** [comment]
> ### Lagrange项目
> OneBot OneBot的
> 
> ### 新需求内容
> 比如说原来的onebot端和服务端是一对一，但是为了服务端的高可用我会希望把它做成集群，所以我希望lgr能直接帮我完成服务端集群多节点的负载均衡

什么意思，一个lgr连多个消息处理端吗？可以试试[Go-Lagrange-Client](https://github.com/2mf8/Go-Lagrange-Client)

**Comment by DarkRRb** [comment]
目前 onebot 就可以一 (Lagrange) 对多 (nonebot 等对接 onebot 的实现)
