### ISSUE TITLE
[Feature Request]: [Lagrange.OneBot] 希望增加"群成员名片修改时间", 但是该事件不属于OneBot

### ISSUE THREAD

**Issue by rongrong1000** [LagrangeDev/Lagrange.Core#633]
### Lagrange项目

OneBot

### 新需求内容

当群成员修改名片时 推送事件, 但是该事件不属于OneBot
不知道有希望增加嘛 (作为拓展事件)

https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E5%90%8D%E7%89%87%E6%9B%B4%E6%96%B0

**Comment by DarkRRb** [comment]
暂时没有支持的想法
