### ISSUE TITLE
[Bug?]: 中断数据库迁移并删除数据库后依然进入迁移流程

### ISSUE THREAD

**Issue by Haocen2004** [LagrangeDev/Lagrange.Core#640]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Audio

### 所使用/依赖的Lagrange项目对应的commit

93c35bc5605d0f8565ca9e26d909233247d3e985

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

1.触发一次数据库迁移
2.在迁移过程中中断 并删除 lagrange-qq.db 和 lagrange-qq-log.db 文件
3.启动lagrange 此时依然进入数据库迁移

### 期望的结果是什么？

直接启动

### 实际的结果是什么？

进入数据库迁移模式 需要手动再次重启

### Trace 级别日志记录（可选）

```Shell
Lagrange.OneBot Version: 0.0.3+93c35bc5605d0f8565ca9e26d909233247d3e985
warn: Lagrange.OneBot.LagrangeAppBuilder[0]
      Depending on the size of the database will consume some time and memory
warn: Lagrange.OneBot.LagrangeAppBuilder[0]
      Please restart the program after indexing is complete
```

**Comment by DarkRRb** [comment]
第一次创建数据库会判断为未索引过, 因此会进入索引流程, 将在后续优化
