### ISSUE TITLE
[Bug?]: 打开/关闭全体禁言接收到的notice是错的

### ISSUE THREAD

**Issue by KINOVE** [LagrangeDev/Lagrange.Core#648]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

28d0cdd58c8d76887b5d080413b89433985ee33a

### 运行环境

Linux

### 运行架构

x64

### 连接方式

反向 WebSocket

### 重现步骤

打开/关闭全体禁言

### 期望的结果是什么？

打开全体禁言 -> 接收到notice.group_ban.ban
关闭全体禁言 -> 接收到notice.group_ban.lift_ban

### 实际的结果是什么？

一共6个群，只有一个接收到的是对的，其他接收到的通知都是错的，基本上都是lift_ban

![89a651d2df502fd521be2dc7a03c3f7b](https://github.com/user-attachments/assets/15ee5581-835b-4fba-8d00-32b5ab6daff2)

![bcfcddaae6533b91d0bf9eb4773217bb](https://github.com/user-attachments/assets/8b7f364a-d0a0-4500-88ca-93509e6d4e93)

**Comment by DarkRRb** [comment]
fixed in #647
