### ISSUE TITLE
[FATAL]: Tag: 禁止登录

### ISSUE THREAD

**Issue by wzddong** [LagrangeDev/Lagrange.Core#65]
[2024-01-13 23:20:18] [WtExchangeLogic] [FATAL]: Tag: 禁止登录
State: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
trce: Lagrange.Core.BotContext[0]

**Comment by Linwenxuan05** [comment]
请配置signserver

wzdong ***@***.***>于2024年1月13日 周六下午11:18写道：
