### ISSUE TITLE
[Feature Request]: Bot断连时上报事件或者与Onebot断开连接

### ISSUE THREAD

**Issue by jiangyuxiaoxiao** [LagrangeDev/Lagrange.Core#665]
### Lagrange项目

OneBot

### 新需求内容

在bot被踹下线后，没有向`onebot`上报相关事件，也没有与`onebot`断开连接，相关的日志为
![39582ffaf318eaffd86ec219120c2046](https://github.com/user-attachments/assets/d77647a0-bc16-4707-aada-1d25360018c1)

+ 没有向onebot上报相关事件的体现为：尽管在`Lagrange.Core`中实现了`OnBotOfflineEvent`，但是并没有在`Lagrange.Onebot`中引用
+ 没有与onebot断开连接体现为：无法触发`nonebot`的`on_bot_disconnect`函数

同时在`get_bot_status` API中bot的在线状态似乎永远为`True`：
![image](https://github.com/user-attachments/assets/0f5b346f-1fbd-47d2-981e-b330d4a2f905)

希望能添加功能让lgr向onebot主动上报断连事件或者直接断开连接，便于bot框架这边处理断连后的操作

**Comment by RTAkland** [comment]
是让lgr发送给客户端断开链接后发生的事件？

**Comment by jiangyuxiaoxiao** [comment]
> 是让lgr发送给客户端断开链接后发生的事件？

发送给客户端告知已经断开连接

**Comment by RTAkland** [comment]
好像确实需要这个事件下发, 不然机器人寄了都不知道
