### ISSUE TITLE
[Bug?]: ocr_image 出来的效果非常差。

### ISSUE THREAD

**Issue by Yan-Zero** [LagrangeDev/Lagrange.Core#690]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

606f3765afc690ad7d68a86249dde8cecbfd55ea

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

使用最新的 orc_image 的 api
![caba08940e8c1dae232d7993db329155_720](https://github.com/user-attachments/assets/93d0e1d5-648d-4542-8f95-b0d578bb5c54)
对一张图片进行ocr

多次测试，对于不同的图片 ocr 效果一样也很差。

### 期望的结果是什么？

能正确识别出来：我只是个笨蛋，也没有你聪明。

### 实际的结果是什么？

![283abb604dad8d14dcf9586f59d288b5](https://github.com/user-attachments/assets/d305eee1-17f1-40c3-b88e-267c9ef9bc65)

**Comment by pk5ls20** [comment]
![Screenshot_20241123_185745_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/2bf6363c-915c-49d4-b6c7-f132736f7eb6)

tx的ocr是这样的

**Comment by pk5ls20** [comment]
> 多次测试，对于不同的图片 ocr 效果一样也很差。

请使用手机QQ的提取文字功能对这些图片进行识别。
如果从Lagrange获取到的识别结果和手机QQ获取到的识别结果精度上存在较大差异，请重新打开一个issue。
