### ISSUE TITLE
[Bug?]: get_group_member_list 接口返回的成员信息有字段与 OneBot 标准不符？

### ISSUE THREAD

**Issue by NingmengLemon** [LagrangeDev/Lagrange.Core#695]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

https://github.com/LagrangeDev/Lagrange.Core/commit/5e7072c641d738749c016bd5d54a8af2761ce166

### 运行环境

Linux

### 运行架构

x64

### 连接方式

正向 WebSocket

### 重现步骤

请求 `get_group_member_list` 接口

### 期望的结果是什么？

`card` 字段不应该可以给空，就像 OneBot-11 文档中所说的那样，这时似乎应该给一个空串： <https://github.com/botuniverse/onebot-11/blob/master/api/public.md#get_group_member_list-%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E5%88%97%E8%A1%A8>

### 实际的结果是什么？

![Snipaste_2024-11-25_21-55-33](https://github.com/user-attachments/assets/348a4b15-c0b4-4ff4-8987-e1d118547814)

### 补充说明（可选）

而且其他字段为空时均为空串，只有这个字段为空时给空，感觉也怪怪的（）

**Comment by ishkong** [comment]
1. 在OneBot11标准中并未要求项必须有值
2. 该值来自于与tx通信PB中的第8字段，为空应该是tx就给的是空
3. 这不应该属于bug，但是你可以提交一个feature requests让开发组讨论是否对该值进行优化
