### ISSUE TITLE
[Bug?]: 消息事件收到的 File 消息段的格式与文档不符

### ISSUE THREAD

**Issue by RF-Tar-Railt** [LagrangeDev/Lagrange.Core#708]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

0d27babeddbdb4dfa77637135abb0a2fbd1bdd04

### 运行环境

MacOS

### 运行架构

arm64

### 连接方式

正向 WebSocket

### 重现步骤

收到携带 File 消息段的消息事件

### 期望的结果是什么？

![image](https://github.com/user-attachments/assets/0853a42c-21ba-462b-8075-f7bbad9a45eb)
消息段内容与文档相符

### 实际的结果是什么？

<img width="616" alt="6653be5abcb8b977531760f1658405ec" src="https://github.com/user-attachments/assets/dd0f0e46-c204-4c6d-ae9b-3d96c89f8a73" />

file_name => filename

file_id => id

**Comment by ishkong** [comment]
该文档已经废弃，且OneBot11里未明确定义，同时上述file的部分信息tx并不会推送，所以为了保证准确性，请使用对应的api获取

关于字段名，会修改

关于该消息段在lagrange里的定义，请参考如下：

位于**消息**里（指推送和`get_msg`获取）的**FileSegment**将暂时只会包含一下信息：

`file_name`: 文件名字，用于使用获取文件下载链接后，确定文件名
`file_id`: 文件id，刷新链接必要的内容
`file_hash`: 刷新私聊文件下载链接可能需要用到的参数，从目前情况来看，不用该值也能获取到，保存备用，**群聊文件该值为空**
`url`：收到有文件上传通知时可用的下载链接，非长期有效链接，不确定失效时间

备注：若群文件上传，没有将文件上传到根目录下，该消息段不会有任何提示。因为若发生文件位置移动，tx也不会有通知，所以群文件还需要自行确定文件所处位置
