### ISSUE TITLE
[Bug?]: QQ版本过低

### ISSUE THREAD

**Issue by MingriLingran** [LagrangeDev/Lagrange.Core#715]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

Audio

### 所使用/依赖的Lagrange项目对应的commit

a4903fecfb8c141b968afe9e0f07405d83a0ecba

### 运行环境

Windows

### 运行架构

x64

### 连接方式

None

### 重现步骤

下载构建版[Lagrange.OneBot](https://github.com/LagrangeDev/Lagrange.Core/actions/runs/12481710652)
运行扫码登录后,会出现版本过低的提示,并拒绝登录
![图片](https://github.com/user-attachments/assets/bcd382e2-0a87-436d-8749-e3ba986e90f1)

### 期望的结果是什么？

正常登录

### 实际的结果是什么？

版本过低的提示,并拒绝登录

**Comment by godlikewangjun** [comment]
我也是啊，用不了了

**Comment by DarkRRb** [comment]
请更新 30366 签名, 详细方法移步至 tg 或 QQ 群

**Comment by hxy112292** [comment]
请问tg 或 QQ群的地址有吗？

**Comment by hxy112292** [comment]
请问tg 或 QQ群的地址有吗？

**Comment by wcwq98** [comment]
> 请更新30366签名，详细方法移步至tg或QQ群

有群吗

**Comment by pk5ls20** [comment]
请仔细阅读readme

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EvanJaye** [comment]
有群吗？
