### ISSUE TITLE
RawMessage is always empty

### ISSUE THREAD

**Issue by NepPure** [LagrangeDev/Lagrange.Core#72]
https://github.com/LagrangeDev/Lagrange.Core/blob/592761dc55442c42701ebf335f477c189dd660f0/Lagrange.OneBot/Core/Entity/Message/OneBotGroupMsg.cs#L24

应该是忘了赋值，测试复读禁言功能发现，因为都是空的，现在说话的群友都被禁言了🤣

**Comment by Linwenxuan05** [comment]
不准备支持CQCode
